### ISSUE TITLE
Use relevance from ES in course search results

### ISSUE THREAD

**Issue by mbenadda** [openfun/richie#1002]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
Richie's course search engine was built with a few assumptions in mind. One of them is that the number of courses in a given portal is low (speaking in terms of Search, meaning <1000) and that most (~90%) of these are not accessible to the typical user at any given time, as MOOCs have a set duration and a short duration during which users can enroll.

Given this assumption, we discard document relevance scores and instead sort them into buckets depending on a number a factors, buckets which then have their own sorting criteria. We're treating ES search as pure filtering, including for full-text searches.

While this produces good results in some cases, it can break down somewhat when the starting assumptions are challenged. Such as when the number of available courses is larger.

**Describe the solution you'd like**
We should figure out a way to use relevance in our Search results, at least for courses which are available to the user at the time they run their search.

We could update our sorting script to assign a factor to our buckets and combine it with the actual relevance of documents (soft bucketing). This could give similar results to what we have now in most cases, except very relevant documents would surface in more searches.

Another potential idea would be to keep documents segregated through our buckets (hard bucketing) and use relevance to order documents inside some of them (of between a subset of our buckets, eg. between "currently running MOOC" & "self-study open archive courses").

**Describe alternatives you've considered**
See above 👆

**Discovery, Documentation, Adoption, Migration Strategy**
Not much to discover here, users will just have better search results. Richie operators might need to re-index all documents depending on the changes we actually have to make.

We might also consider documenting our indexing and general search relevance/sorting strategy on our documentation website. This would give other Richie operators more insight into how things are done, enabling them to help us improve Richie or to just change things up on their own instance.

**Do you want to work on it through a Pull Request?**
👍

**Comment by jbpenrath** [comment]
Related code : https://github.com/openfun/richie/blob/master/src/richie/apps/search/indexers/courses.py#L89

**Comment by sampaccoud** [comment]
This was done in PR https://github.com/openfun/richie/pull/1295
