### ISSUE TITLE
Course list (aka search page) drop every metas

### ISSUE THREAD

**Issue by sveetch** [openfun/richie#1027]
## Bug Report

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).
The meta tags from the "base.html" template should be always present on every pages.

**Actual Behavior**
The meta tags from the "base.html" are not present on the Course list page.

This is because the "search.html" template override the whole "meta" block:

https://github.com/openfun/richie/blob/master/src/richie/apps/search/templates/search/search.html

**Steps to Reproduce**
1. Go to https://demo.richie.education/
2. Look for the site favicon in your browser tab, you should see the red book icon. Or more precisely you can watch in page HTML source code to see there is a lot of meta tags.
3. Open https://demo.richie.education/fr/cours/ in a new tab, the favicon is not present anymore and more precisely in the page HTML source code you can see almost every meta tags are absent.

**Environment**
- Richie version: 2.0.0-beta.6
- Platform: Linux

**Possible Solution**
Use the `{{ block.super }}` in the "meta" block (preferably at the beginning) and the initial content from "base.html" will be here again.

**Comment by igobranco** [comment]
The PR https://github.com/openfun/richie/pull/1457 fixes this issue.
