### ISSUE TITLE
Some links are broken on demo homepage

### ISSUE THREAD

**Issue by Eskimon** [openfun/richie#1071]
## Bug Report

**Expected behavior/code**
Some links are broken on the front page of the demo at `demo.richie.education`. The "A propos" and "Plan du site" links in the footer are redirecting to localhost instead of the right domain. Some meta properties are also bugged.

**Actual Behavior**
The links are build like `https://localhost:8080/fr/the/page/` instead of `https://demo.richie.education/fr/the/page/` 

**Steps to Reproduce**
- Open the demo at : <https://demo.richie.education/fr/>
- Scroll down to the footer
- Open the "A propos" or "Plan du site" links
- `localhost:8080` instead of `demo.richie.education` opens

**Possible Solution**
 According to <https://github.com/openfun/richie/blob/6cb4891d5e73637d96fd7dc28838a7b2b6bafe44/src/richie/apps/core/helpers.py#L123>, the `django.contrib.sites.models.Site` seems to not be set. The solution is to set it to the proper value in the database

**Additional context/Screenshots**
This problem can also be found when displaying the source. Some meta properties ("og:image" and "og:url") don't link to the right domain.

**Comment by jmaupetit** [comment]
Thanks for the report! :pray:

**Comment by sampaccoud** [comment]
@Eskimon Yes this was due to the "Site" model not being set in our demo. I updated the nightly script that resets the demo and all links seem to be working now.
