### ISSUE TITLE
Sentry is not configured correctly

### ISSUE THREAD

**Issue by lunika** [openfun/richie#1089]
## Bug Report

**Expected behavior/code**

When an issue is reported to sentry we want to know the environment and the release where the issue occurs

**Actual Behavior**

When an issue is caught and reported to sentry, we don't have the real environment and release information. Instead we have something like `<property object at 0x7f2fc9fe0c20>`

**Steps to Reproduce**
1. Configure your environment with a valid `SENTRY_DSN`
2. shut down the database
3. send a request to Richie. Without a database an exception will be thrown
4. look in sentry environment and release values.

**Environment**
- Richie version: 2.0.0
- Platform: docker

**Possible Solution**
 sentry is configured in [settings.py](https://github.com/openfun/richie/blob/bead3d66af63d9a336a661a6afaa22fca059dbad/sandbox/settings.py#L407-L424). The method used a `classmethod` decorator and as I understand the `cls` parameter is not an instance of the class but the uninstanciated class. To configure sentry we call methods using a `property` decorator, calling them statically like we do return a `property` object and does not call the `getter` method attached to the decorator. Creating static method can resolve the issue or we have to find a way to instantiate the class.

**Comment by lunika** [comment]
Here is the fix I made on marsha https://github.com/openfun/marsha/pull/760

**Comment by jbpenrath** [comment]
https://github.com/openfun/richie/pull/1225
