### ISSUE TITLE
Upgrade html5lib to >0.9999999

### ISSUE THREAD

**Issue by jmaupetit** [openfun/richie#110]
## Purpose

This is a follow-up issue of PR #103 [1].

Due to security issue, we need to upgrade `html5lib` to a release `>1.0b8`:

> The serializer in html5lib before 0.99999999 might allow remote attackers to conduct cross-site scripting (XSS) attacks by leveraging mishandling of the < (less than) character in attribute values.

`html5lib` is a dependency of `djangocms-text-ckeditor`, the problem has already been reported [2] and this upgrade is still pending [3].

[1] https://github.com/openfun/richie/pull/103#issuecomment-385416784
[2] https://github.com/divio/djangocms-text-ckeditor/issues/403
[3] https://github.com/divio/djangocms-text-ckeditor/pull/464

## Proposal

IMO we have two options here:

1. wait for a new release of `djangocms-text-ckeditor` bundled with a recent release of `html5lib`, or,
2. use an alternative content editor for Django CMS

**Comment by rmoch** [comment]
Removed in fc81661ce1c23adfc16ea0fb74ab8d66956c69f8
