### ISSUE TITLE
Allow customizing the placeholder text in the search bar input field

### ISSUE THREAD

**Issue by sampaccoud** [openfun/richie#1100]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
On some sites powered by Richie, we are asked to customize the placeholder text in the search bar:
![image](https://user-images.githubusercontent.com/1427165/90760994-fd659280-e2e2-11ea-89e8-649208eff285.png)

**Describe the solution you'd like**
Customizing this text can be done via a template, translation or code override by the developper. It does not have to be updatable by CMS users.

**Discovery, Documentation, Adoption, Migration Strategy**
I noticed that on Richie's demo site, the french version of this placeholder text is not the translation of the english version.

![image](https://user-images.githubusercontent.com/1427165/90761293-795fda80-e2e3-11ea-8bcc-395966b590fc.png)

**Comment by jbpenrath** [comment]
Sites powered by Richie can now override frontend translations.
#1162
