### ISSUE TITLE
Make scrolling smoother on the search page

### ISSUE THREAD

**Issue by sampaccoud** [openfun/richie#1103]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
When changing page on the search page, the scroll-up happens at the same time as the switch to new results, which flickers confusingly. In case the request for the new page takes time to get a response, the switch to new results can even happen after the scroll-up is finished which is even more confusing.

**Describe the solution you'd like**
Wait for the response to the new page request before triggering the scroll-up.

**Comment by mbenadda** [comment]
Closed by #1117
