### ISSUE TITLE
Add & configure raven.js

### ISSUE THREAD

**Issue by jmaupetit** [openfun/richie#113]
## Purpose

As mentioned in #112, we need to integrate and configure [Raven.js](https://github.com/getsentry/raven-js) to also catch front-end application errors [1, 2].

## Proposal

- [ ] load the `raven` template tag library in the base Django template
- [ ] define a `sentry_public_dsn` JavaScript variable in a `script` block from the Django base template (using `{% sentry_public_dsn %}`)
- [ ] add `raven.js` to front-end dependencies and build
- [ ] configure the client via `Raven.config(sentry_public_dsn).install()`
- [ ] wrap front-end app using `Raven.context`

## References

[1] https://docs.sentry.io/clients/python/integrations/django/#using-with-raven-js
[2] https://docs.sentry.io/clients/javascript/

**Comment by jmaupetit** [comment]
I do agree that it's way more clean to load raven as an ES6 module :heart:

But, as we have an hybrid approach concerning the front-end, we may miss application failures for everything related to DjangoCMS' or any third-party JavaScript app loaded by the CMS.

Hence, we need to define a specific block in our base Django template to load & configure Raven.js. By doing so, we will be able to override this behavior when only our front-end app is loaded.

WDYT?

**Comment by mbenadda** [comment]
I overlooked the third-party JS part. I think on the front-office there would probably be no other JS than ours involved but on the back-office it's a different story and we need to catch errors there too.

Therefore, it's probably better to just reuse the global-scope Raven.js in our front code than to load it twice. (Maybe adding some logic to load it if it cannot be detected in the global scope?)

**Comment by jmaupetit** [comment]
> Maybe adding some logic to load it if it cannot be detected in the global scope?

Yup. Good idea!

**Comment by mbenadda** [comment]
Just a quick note to point out that is is probably affected by #72 and generally by the way we want to split our apps into separate reusable packages.

It's probably a good idea to wait until the split is effective to work on sentry/whatever reporting.
