### ISSUE TITLE
EDX User info does not replicate on Richie

### ISSUE THREAD

**Issue by jbpenrath** [openfun/richie#1143]
## Bug Report

**Expected behavior/code**
Account information from OpenEDX should be replicated on Richie.

**Actual Behavior**
Only fields provided by the default django User model are replicated on Richie.

**Steps to Reproduce**
1. Register on OpenEDX by specifiyng a fullname.
2. Login on Richie
3. In the user menu, the user's fullname should be displayed but it is its username.

**Environment**
- Richie version: 2.0.0-beta.14
- Platform: docker

**Possible Solution**
Create a custom User model on Richie to add extra fields provided by OpenEDX (fullname, language)

**Comment by sampaccoud** [comment]
Closing as we decided to walk away from the oauth2 SSO and share a cross domain session cookie with OpenEdX. The move is implemented in PR https://github.com/openfun/richie/pull/1150.
