### ISSUE TITLE
Does Richie support custom theming and multi-tenancy?

### ISSUE THREAD

**Issue by OmarIthawi** [openfun/richie#1148]
**Topic**
We're exploring an alternative content management system for Tahoe to host basic pages like `/courses`, `/` (homepage), `/about`, etc. Tahoe is multi-tenant and we need to support multiple instances (either via Docker, or natively in Django).  

**Question**

 - Does Richie support theming? If yes, to what extent?
 - Does Richie support multi-tenancy? I suppose Docker is the way to go. Right?

**Comment by sampaccoud** [comment]
Hi Omar! Yes Richie is designed for theming and is installed in your own DjangoCMS project as a third party application. 

You can for example:
- override or extend Django templates the Django way,
- derive from richie's sass files and rebuild the css after customizing it,
- override React components.

We are running a handful of sites based on Richie by building custom Docker images in what we call a site factory. You can see at https://github.com/openfun/richie-site-factory.

Feel free to clone it and use it as a boilerplate. As it comes with tools and CI to quickly maintain many Richie sites with specific customizations or not.

**Comment by OmarIthawi** [comment]
Thanks a lot Samuel for letting me know! I'll close the issue.
