### ISSUE TITLE
By `make run`, I get this error: lookup elasticsearch on 127.0.0.11:53: no such host!

### ISSUE THREAD

**Issue by perpi** [openfun/richie#1183]
I installed the program with this series of commands:

    $ git clone https://github.com/openfun/richie.git
    $ chown "$USER":"$USER" -R richie/
    $ chmod g+rwx -R richie/
    $ cd richie/
    $ make bootstrap

Do I have to up the ElasticSearch service myself, or does the Richie do it? Because I'm getting the following error:

    $ make run
    Starting richie_postgresql_1    ... done
    Starting richie_elasticsearch_1 ... done
    Starting richie_app_1           ... done
    Starting richie_nginx_1         ... done
    Wait for services to be up...
    Creating richie_dockerize_run ... done
    2020/11/06 15:31:21 Waiting for: tcp://postgresql:5432
    2020/11/06 15:31:21 Connected to tcp://postgresql:5432
    Creating richie_dockerize_run ... done
    2020/11/06 15:31:25 Waiting for: tcp://elasticsearch:9200
    2020/11/06 15:31:25 Problem with dial: dial tcp 172.18.0.2:9200: getsockopt: connection refused. Sleeping 1s
    2020/11/06 15:31:44 Problem with dial: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
    2020/11/06 15:32:25 Timeout after 1m0s waiting on dependencies to become available: [tcp://elasticsearch:9200]
    make: *** [Makefile:110: run] Error 1

    $ sudo systemctl start elasticsearch
    Failed to start elasticsearch.service: Unit elasticsearch.service not found.

Server: VPS, Ubuntu 20.04.1 LTS
Docker version: 19.03.13, build 4484c46d9d
docker-compose version: 1.27.4, build 40524192
My user `groups`: perpi sudo docker

    $ docker ps
    CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS                            
    NAMES
    4df1832a14a8        nginx                "/docker-entrypoint.…"   39 hours ago        Up 26 minutes       80/tcp, 0.0.0.0:8070->8070/tcp   richie_nginx_1
    dc23429c30b0        richie:development   "/usr/local/bin/entr…"   39 hours ago        Up 26 minutes                                        richie_app_1
    f5de77419fa1        postgres:9.6         "docker-entrypoint.s…"   39 hours ago        Up 26 minutes       5432/tcp                         richie_postgresql_1

    $ docker-compose -p reportportal logs --tail="all" elasticsearch
    Attaching to
    [Nothing here!]

Permissions on folders:

    $ ls -l ~/richie/data/
    total 12
    drwxrwxr-x 2 perpi perpi 4096 Nov  5 00:48 media
    drwxrwxr-x 2 perpi perpi 4096 Nov  5 00:48 smedia
    drwxrwxr-x 2 perpi perpi 4096 Nov  5 00:48 static

**Comment by sampaccoud** [comment]
Hi @perpi 
There is a good chance that your Elasticsearch does not have enough resources to start as explained in this troubleshooting section: 
https://github.com/openfun/richie/blob/master/docs/docker-development.md#troubleshooting

If this does not fix it, could you paste the result of : 
```
docker-compose logs elasticsearch
```

**Comment by perpi** [comment]
Thank you for your prompt answer;

Resources: 12GB Ram / 4 CPU, 250 GB SSD disk

    $ free -h
                  total        used        free      shared  buff/cache   available
    Mem:           11Gi       398Mi        10Gi        14Mi       781Mi        11Gi
    Swap:            0B          0B          0B

    $ top
    top - 16:24:14 up 10 min,  1 user,  load average: 0.19, 0.40, 0.33
    Tasks: 141 total,   2 running, 139 sleeping,   0 stopped,   0 zombie
    %Cpu(s):  2.9 us,  1.8 sy,  0.0 ni, 95.1 id,  0.0 wa,  0.0 hi,  0.0 si,  0.2 st
    ...
        PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
       1904 perpi      20   0  324400  81788  12900 S  17.9   0.7   2:12.09 python
          1 root      20   0  167700  11576   8492 S   0.0   0.1   0:04.48 systemd
          2 root      20   0       0      0      0 S   0.0   0.0   0:00.02 kthreadd
‍‍‍‍‍
`‍‍docker-compose logs elasticsearch | nc termbin.com 9999‍`
Requested logs: https://termbin.com/h2pn

**Comment by sampaccoud** [comment]
OK so the problem is this:
```
[36melasticsearch_1   |[0m [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
```

Look the solution at the link I posted above.
