### ISSUE TITLE
Snapshot are indexed by elasticsearch

### ISSUE THREAD

**Issue by 2018D** [openfun/richie#1207]
## Bug Report

**Expected behavior/code**
Elasticsearch should not index snapshots

**Actual Behavior**
Snapshots are being indexed

**Steps to Reproduce**
1. Snapshot a course
2. Regenerate index (if needed)
3. Find the snapshot among the course

**Environment**
- Richie version: 2.0.0-beta.21
- Platform: 

**Possible Solution**
We had a test named _test_indexers_courses_get_es_documents_snapshots_ that was supposed to make sure snapshot were not indexed.

**Additional context/Screenshots**
[
![Screenshot_2020-12-03 Courses](https://user-images.githubusercontent.com/17911549/101105427-8905e500-359b-11eb-8398-77edc80e9250.png)
](url)

**Comment by sampaccoud** [comment]
Thank you for your bug report @2018D. This bug is solved in PR https://github.com/openfun/richie/pull/1202. Can you test this PR? It should be merged in the coming hours and will greatly simplify course runs and improve the user experience to create/update them.

**Comment by 2018D** [comment]
I tested PR #1202.  Great work 👍.
Sorry for not being able to test it last week. I didn't know you already had something almost ready when i reported this . 
The translation portion for the course run felt weird at first, but i understood how to make it work after a moment.
Thank you !
