### ISSUE TITLE
Error 500 when editor uses a course page template on a page that has no course attached

### ISSUE THREAD

**Issue by jbpenrath** [openfun/richie#1280]
## Bug Report

**Actual Behavior**
On page which is not a course page, editor is allow to change the page template by a course model page. As this template requires to be linked to a course object, an 500 error occured.

**Expected behavior/code**
Richie should not crash after an user action.

**Steps to Reproduce**
1. Login as editor
2. Go to the homepage
3. In the toolbar, navigate to `Page > Templates`
4. Select `Course Page`
3. And then the bug happens!

**Environment**
- Richie version: 2.1.0
- Platform: Mac OS 11.2.1 - Firefox 85.0.2

**Possible Solution**
1. Prevent editor to change page's template to a course template.
2. When a course template is used, check if a course is attached to the page. If not warn editor with an explicit message explaining that he is doing something wrong.

**Additional context/Screenshots**
https://sentry.io/organizations/gip-fun-mooc/issues/2136906474/?project=1198559&query=is%3Aunresolved

**Comment by sampaccoud** [comment]
I vote for solution 2 as solution 1 would require modifying the cms... Should be done for all page extension types...
