### ISSUE TITLE
Problem with dial: dial tcp 172.18.0.2:9200: getsockopt: connection refused. Sleeping 1s

### ISSUE THREAD

**Issue by CaffeinatedStud** [openfun/richie#1307]
Hi.

Installing richie v2.2.0 through docker-compose on a fresh AWS Ubuntu 18.04 instance and getting the following error. Same issue on Ubuntu 20.04

Creating richie-220_dockerize_run ... done
2021/03/13 13:04:25 Waiting for: tcp://postgresql:5432
2021/03/13 13:04:25 Connected to tcp://postgresql:5432
Creating richie-220_dockerize_run ... done
2021/03/13 13:04:27 Waiting for: tcp://elasticsearch:9200
2021/03/13 13:04:27 Problem with dial: dial tcp 172.18.0.2:9200: getsockopt: connection refused. Sleeping 1s
2021/03/13 13:04:28 Problem with dial: dial tcp 172.18.0.2:9200: getsockopt: connection refused. Sleeping 1s
2021/03/13 13:04:29 Problem with dial: dial tcp 172.18.0.2:9200: getsockopt: connection refused. Sleeping 1s
2021/03/13 13:04:30 Problem with dial: dial tcp 172.18.0.2:9200: getsockopt: connection refused. Sleeping 1s
2021/03/13 13:04:31 Problem with dial: dial tcp 172.18.0.2:9200: getsockopt: connection refused. Sleeping 1s
2021/03/13 13:04:32 Problem with dial: dial tcp 172.18.0.2:9200: getsockopt: connection refused. Sleeping 1s
2021/03/13 13:04:33 Problem with dial: dial tcp 172.18.0.2:9200: getsockopt: connection refused. Sleeping 1s
2021/03/13 13:04:34 Problem with dial: dial tcp 172.18.0.2:9200: getsockopt: connection refused. Sleeping 1s
2021/03/13 13:04:35 Problem with dial: dial tcp 172.18.0.2:9200: getsockopt: connection refused. Sleeping 1s

docker -v
Docker version 19.03.6, build 369ce74a3

docker-compose --version
docker-compose version 1.28.5, build c4eb3a1f

Grateful if you could please assist. Thanks.

**Comment by sampaccoud** [comment]
@CaffeinatedStud yes! It's most probably you Elasticsearch that is a bit tight. You can see the solution here:
 https://github.com/openfun/richie/blob/master/docs/docker-development.md#elasticsearch-service-is-always-down

**Comment by CaffeinatedStud** [comment]
Thanks, works now.
Really appreciate your help.
