### ISSUE TITLE
Docker User Production

### ISSUE THREAD

**Issue by aarajbhattarai** [openfun/richie#1338]
I am having problems to to set docker user for production.How do I see the user ?

**Comment by sampaccoud** [comment]
@aarajbhattarai Could you give a little more detail about your problem?
Have you read our explanations in the entrypoint? https://github.com/openfun/richie/blob/master/docker/files/usr/local/bin/entrypoint#L3

**Comment by sampaccoud** [comment]
@aarajbhattarai I'm closing the issue. Don't hesitate to reopen it if you still experience the problem and can give us more details.
