### ISSUE TITLE
Use isort to automate import statements ordering

### ISSUE THREAD

**Issue by jmaupetit** [openfun/richie#139]
## Purpose

[`isort`](https://github.com/timothycrosley/isort) is a wonderful tool to automate import statement ordering, and, it plays well with black. Let's use this to increase our code base quality (and predictability).

## Proposal

- [x] Add `isort` dependency
- [x] Configure isort to play well with Black, see [1, 2]
- [x] Add a CircleCI `lint-back-isort` job that runs `isort` in check mode
- [x] Update README file

[1] https://github.com/timothycrosley/isort#configuring-isort
[2] https://github.com/ambv/black#how-black-wraps-lines

**Comment by sampaccoud** [comment]
+ update README file

**Comment by sampaccoud** [comment]
Points 1 & 2 were addressed in https://github.com/openfun/richie/commit/06e48a3737e09fec9f211337fc20444bcd934ac5
Point 3 was addressed in https://github.com/openfun/richie/commit/c08938aded96630bdccf161fa25f408cfaa78afb
