### ISSUE TITLE
hreflang path is not valid

### ISSUE THREAD

**Issue by jbpenrath** [openfun/richie#1393]
## Bug Report

**Expected behavior/code**
meta hreflang should be properly defined.

**Actual Behavior**
A lighthouse audit shows that hreflang is set with a relative path.

**Steps to Reproduce**
1. Use a chromium browser with lighthouse extension installed
2. Run a SEO audit

**Environment**
- Richie version: 2.7.1
- Platform: Mac OS 11.4 - Chrome 90.0.4430.212

**Possible Solution**
Use an absolute path to define hreflang.

**Additional context/Screenshots**
<img width="719" alt="image" src="https://user-images.githubusercontent.com/9265241/123292576-76410680-d513-11eb-8d6a-d26d34d60700.png">

**Comment by sveetch** [comment]
Richie include a template context processor which ships some basic Site informations like the absolute base URL:

https://github.com/openfun/richie/blob/master/src/richie/apps/core/context_processors.py#L31

It could be used to make URL absolute in meta elements that need it like :

https://github.com/openfun/richie/blob/master/src/richie/apps/core/templates/richie/hreflang.html

Where `{% page_language_url code %}` should be replaced with `{{ SITE.web_url }}{% page_language_url code %}`.
