### ISSUE TITLE
Image display issue on some blog posts

### ISSUE THREAD

**Issue by NamFra** [openfun/richie#1424]
## Bug Report

**Expected behavior/code**
The image width of the blog post cover must be the same as the column width of the article, regardless of the screen size.

**Actual Behavior**
On some blog posts and depending on the screen size, the image width is smaller than the column width.

**Steps to Reproduce**
1. Open the following articles:
- https://www.fun-mooc.fr/fr/actualites/votez-pour-le-mooc-de-lannee/
- https://www.fun-mooc.fr/fr/actualites/informatique-formez-vous-et-stimulez-votre-carriere/
2. On each page, open the devtools in your browser, switch to the "device toolbar" and select Ipad Pro (1024x1366)
3. See the correct display of the image (950x576 px) on the first blog post:

![ok width inf 1000px](https://user-images.githubusercontent.com/23249365/129198258-43289a35-8e8d-4261-9d61-c5d4ba4de979.png)

4. See the reduced display of the image (1500x887 px) on the second blog post: 

![nok width sup 1000px](https://user-images.githubusercontent.com/23249365/129210892-f401731c-38d8-403b-be9d-b9bae41e250e.png)

**Environment**
- Richie version: 2.7.1
- Platform: Docker

**Possible Solution**
This display issue seems to occur only when the width of the blog post cover is greater than 1000px.
The `srcset` attribute for images wider than 1000px resizes them to 1000x1000.
[https://github.com/openfun/richie/blob/d87d01bbf69a1e8bcb5b63a714f1595dfb64f70a/src/richie/apps/courses/templates/courses/cms/blogpost_detail.html#L103](https://github.com/openfun/richie/blob/d87d01bbf69a1e8bcb5b63a714f1595dfb64f70a/src/richie/apps/courses/templates/courses/cms/blogpost_detail.html#L103)

**Additional context/Screenshots**
Note that the blog posts glimpses have the same `srcset` and that the 2000w ratio is 2000x2000 for both the blog posts glimpses and details.
[https://github.com/openfun/richie/blob/d87d01bbf69a1e8bcb5b63a714f1595dfb64f70a/src/richie/apps/courses/templates/courses/cms/fragment_blogpost_glimpse.html#L16](https://github.com/openfun/richie/blob/d87d01bbf69a1e8bcb5b63a714f1595dfb64f70a/src/richie/apps/courses/templates/courses/cms/fragment_blogpost_glimpse.html#L16)

**Comment by jbpenrath** [comment]
As a workaround, what do you think to replace :
```python
{% with category_variant="tag" has_link=False %}
    {% show_placeholder "categories" blogpost_page %}
{% endwith %}
```

by 

```python
{% get_page_plugins "categories" blogpost_page as category_plugins %}
{% with category_variant="tag" has_link=False %}
    {% for plugin in category_plugins %}
        {% render_plugin plugin %}
    {% endfor %}
{% endwith %}
```

Or do you think we should totally remove the use of `hasLink` ?
