### ISSUE TITLE
Elasticsearch 7.0 compatibility

### ISSUE THREAD

**Issue by IDerr** [openfun/richie#1428]
Hello Richie team,

I have seen that a elasticsearch 6 is needed to run richie.
Is there any plan to move to ES 7 or is it already compatible ?

Thanks a lot for your work !

**Comment by sampaccoud** [comment]
Yes somebody run the test suite on ES7 à while ago and it passed!

We can upgrade the project but add a job in the CI to run the tests against both ES6 and ES7. If you want to submit a PR it will be welcome. Otherwise we will do it asap.

**Comment by IDerr** [comment]
Hi Samuel, 

I've forked the repo, and done some code changes for ES7, unfortunately, there's quite a lot of changes between those two versions

First, I have encountered an error during the index creation, it is linked with the indexing part,  a new field needs to be added:  max_ngram_diff (https://github.com/IDerr/richie/commit/6ab7a88c72a08948f2ce2ec12d7eb8d03691a80b)

Second change, ES 7.0 introduced type less api by default, which means some code changes : 
https://www.elastic.co/blog/moving-from-types-to-typeless-apis-in-elasticsearch-7-0
you can bypass code changes with the keyword include_type_name in the index_creation, get_mapping and put_mapping.
The keyword include_type_name has been introduced only for migration to ES 7.0 and will be removed in ES 8.0, so all the typed api calls in Richie needs to be removed.

I have done some work in my forked repo (https://github.com/IDerr/richie/), I don't think I'll have much more time this week-end to get the work finished... (Two failed tests remaining, both due to changes in the API responses...)

I'll fix the linting issues, if you want to base your code on mine, but I think it's better to switch to the type less API to ensure the compatibility with newer version of ES 

Thanks again for your work :)

PS: Is there any more "active" way to get in contact with the funmooc team (Slack/Gitter or sth like that ?)

**Comment by sampaccoud** [comment]
We decided to open a Slack. Still looking for a name :sweat_smile:

**Comment by IDerr** [comment]
Thanks for creating one !

**Comment by sampaccoud** [comment]
The upgrade to ES7 requested in this issue is being handled in PR https://github.com/openfun/richie/pull/1434.

**Comment by mbenadda** [comment]
@IDerr Richie (`master`, and the next upcoming released version) should not work with ElasticSearch 7! Please let us know/reopen the issue if you still encounter ES7 compatibility issues.

**Comment by IDerr** [comment]
Thanks for your great work ! 
I'll test it next week :D
