### ISSUE TITLE
Can not configure JS_COURSE_REGEX with backslash on regex

### ISSUE THREAD

**Issue by igobranco** [openfun/richie#1440]
## Bug Report

**Expected behavior/code**
When configuring the `JS_COURSE_REGEX` Django setting with a value like described in the documentation:
```
^https://lms\.example\.com/courses/(.*)/course/?$
```

The _Courses_ search page don't work because the JavaScript that starts the richie frontend has a syntax error.

JS console log message: `Uncaught SyntaxError: Unexpected token . in JSON at position 381`

The code generated by the Richie back end to be assigned to the `window.__richie_frontend_context__` JS variable raises a parsing error on the brower.

Generated JS that raised the error during JSON parse.
```
"course_regexp": "^https://lms\\.example\\.com/courses/(.*)/course/?$"
```

**Steps to Reproduce**
From a running local demo-site, change the file `env.d/development/dev` content with:
```
# Authentication Backend
AUTHENTICATION_BASE_URL=http://localhost:8073
AUTHENTICATION_BACKEND=base

# LMS Backend
EDX_BASE_URL=http://localhost:8073
EDX_BACKEND=richie.apps.courses.lms.edx.EdXLMSBackend
EDX_JS_BACKEND=openedx-hawthorn
EDX_COURSE_REGEX=^https://lms\.example\.com/courses/(?P<course_id>.*)/course/?$
EDX_JS_COURSE_REGEX=^https://lms\.example\.com/courses/(.*)/course/?$
```

Start the richie
```
make run
```

The page http://localhost:8070/en/courses/ won't start the react frontend that searches courses.

This only occurs when we include a backslash on the `JS_COURSE_REGEX`.

**Comment by jbpenrath** [comment]
Wow big issue, thanks 🙏 

To inject `__richie_frontend_context__` we are using `JSON.parse` but the regexp you pass contains unescaped characters (`\`). I found an easy fix (just use `escapejs` template tag in place of `safe`), I just have to update our tests. I keep you up to date when I will open a PR to fix that !
