### ISSUE TITLE
Add visible field to course run

### ISSUE THREAD

**Issue by igobranco** [openfun/richie#1502]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
When using a course run synchronization mode with `sync_to_public` all the course runs changes are visible to the general public. Nevertheless, when a partner decides to create a new course run, with slitly changes on the previous course runs of the same course, that new course run is automatically shown to the public. We think that should be possible to create a new course run, but without being visible to the students.

**Describe the solution you'd like**
When using the Open edX has LMS, the Open edX Studio has an option that changes its visibility on the catalog ( _Studio > Course X > Settings > Advanced settings > Course Visibility In Catalog_ )

Field description:
> Defines the access permissions for showing the course in the course catalog. This can be set to one of three values: 'both' (show in catalog and allow access to about page), 'about' (only allow access to about page), 'none' (do not show in catalog and do not allow access to an about page).

So, if we add a CourseRun `visible` field, that could be updated using the `course_runs_sync` Richie API, then it would be possible to Richie to has a better Open edX compatibility.

On the repo [richie-openedx-sync](https://github.com/fccn/richie-openedx-sync) I would sync it like:
* 'both' ==> course run visible
* 'about' ==> course run hidden
* 'none' ==> course run hidden

Also include the Course Run `visible` field to the Richie Course settings page.

The hidden course run could be shown to the course page administrator with different style (underline, italic and/or grey).

**Describe alternatives you've considered**
None.

**Discovery, Documentation, Adoption, Migration Strategy**

Mockup of the idea:
![course_run_visible](https://user-images.githubusercontent.com/67018/139236166-0a435af5-d2c6-41db-9ebe-76c29eee4d74.png)

**Do you want to work on it through a Pull Request?**
I could add the new field similar to the _enrollment_count_ I sent on previous commits and then add the behavior described early on the course page.

**Comment by sampaccoud** [comment]
@igobranco Since "about" corresponds to "only allow access to about page", I would say we expect the course to be shown on the course page and only hide it if we select "none"?

**Comment by igobranco** [comment]
After discussing with the @sampaccoud it was discussed another approach:
Synchronize the information from Open edX like it is and implement the behavior described on the Open edX on Richie.

The only "problem" is that on Open edX the course team is managing a course run, but on Richie what it's put on the catalog is a course and not a course run. 

Q: What should happen when we have different course runs with different catalog visibility ?
R: One of the possibilities is Richie use the most important one. 
1- If a course has 2 runs one 'both' and another 'about', then the course should has the 'both' behavior. 
2- If a course has 2 runs one 'about' and another 'none' then the course shouldn't be on the course catalog.
3- If a course has only a single run with its catalog visibility has 'none' then its course page shouldn't be published.

**Possible states of the catalog visibility of a course run**
* 'both' - show in catalog and allow access to about page,
* 'about' - only allow access to about page, 
* 'none' - do not show in catalog and do not allow access to an about page.

Q: What should happen if a course has 2 course runs with one with 'both' on the course visibility and another with 'none' ? Should both course runs be visible? 
R: I think only the 'both' course run should be visible. When on the edit mode of the course page, the 'none' course should be visible with a different style and a comment it isn't visible.

**Alternatives**
The draw back that I view is: it could be kind of strange to the user to manage the catalog visibility of a course on its runs.
Richie already has features like to toggle the "Is listed" field _(Tick if you want the course to be visible on the search page.)_
And Django CMS also permit to remove the visibility of a course page.

Why not implement a simpler approach nicer to Richie to only add a visible field on course run? I think simpler is better. Nevertheless the is `visible` field could also be added to the `course_runs_sync` API and on the repo [richie-openedx-sync](https://github.com/fccn/richie-openedx-sync) could be a feature toggle to synchronize it or not ('both' & 'about' ==> True ; 'none' ==> False).

**Comment by sampaccoud** [comment]
My understanding was that we leave the course visibility and indexability to richie and synchronize the visibility field from openedx with a visibility field on the course run in richie.

So, on a given course in richie, 
- the course runs indexed in Elasticsearch are only those who have a visibility set to "both"
- the course runs visible on the course detail page are only those who have a visibility set to "both" or "about"

I think this will seem coherent to userss in OpenEdX... they are choosing the visibility of their course run on the course and not of the related course... The visibility of the course is handled in Richie independently (and it makes sense since this concept of course does not exist in OpenEdX?).

An alternative would be to add a setting in Richie to choose to automatically hide a course which does not have any open or future course run...

**Comment by igobranco** [comment]
@sampaccoud I like your first solution.
