### ISSUE TITLE
Missing migrations

### ISSUE THREAD

**Issue by igobranco** [openfun/richie#1543]
There are missing migrations to be created.

When we run makemigrations it generates 2 new files.
```bash
docker-compose run app python sandbox/manage.py makemigrations
```

Missing changes:
1. course effort
2. course run enrollment_count
3. glimpse  variant

Suggestion changes:
- [ ] Add the missing migrations
- [ ] Change CI to prevent accept a model change without its django migration

**Comment by igobranco** [comment]
@sampaccoud can I send a PR to add the missing Django Migrations ?
What do you think about adding a CI step to prevent we don't forget to add migrations?

**Comment by sampaccoud** [comment]
No we purposely leave some migrations for breaking change and handcraft each migration. It is not a problem to have a delta between what the Django command proposes and what we want to have in our code base. Removing fields for example must be delayed to a version down the road to ensure smooth blue/green deployments.

**Comment by igobranco** [comment]
Ok, it makes sense.
