### ISSUE TITLE
Error synchronizing Richie <-> Tutor with the tutor-richie plugin

### ISSUE THREAD

**Issue by sion42x** [openfun/richie#1544]
## Bug Report

**Expected behavior/code**
Syncing course runs with OpenEDX using the correct secret key and course link works as expected.

**Actual Behavior**
Automatic syncing between OpenEDX and Richie are not working, resulting in the following error in the logs:

```
cms_1 | 2021-12-15 13:01:38,256 ERROR 8 [richie.sync] [user 6] [ip 72.218.28.34] sync.py:67 - Could not synchronize course course-v1:Edunomic+CS101+2014_T1 with Richie. Response: {"resource_link":["Unknown course: CS101."]}
```

Further, a manual attempt was made using the correct secret key and course URL in the LMS, resulting in the same error.

**Steps to Reproduce**
1. Install tutor with OpenEDX lilac
2. Install the tutor-richie plugin
3. Create a course in studio
4. Observe failed sync
5. Attempt a manual sync:

```
Python 3.7.12 (default, Oct 22 2021, 17:50:30)
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import hashlib
>>> import hmac
>>> import json
>>> import requests
>>> data = {
    "resource_link": "https://edunomic.academy/courses/course-v1:Edunomic+BC101+2021_Q4/course",
    "languages": ["en"]
}
>>> signature = hmac.new(
... "SECRET_KEY_GOES_HERE".encode("utf-8"),
... msg=json.dumps(data).encode("utf-8"),
... digestmod=hashlib.sha256,
... ).hexdigest()
>>> response = requests.post(
... "https://courses.edunomic.academy/api/v1.0/course-runs-sync/",
... json=data,
... headers={"Authorization": "SIG-HMAC-SHA256 {:s}".format(signature)},
... )

>>> print(response)
<Response [400]>
>>> print(response.content)
b'{"resource_link":["Unknown course: BC101."]}'
```

**Environment**
- Richie version: 2.8.1
- Platform: tutor-richie (docker container alongside tutor OpenEDX)

**Comment by sampaccoud** [comment]
@sion42x for the synchronization to work, you must first create a syllabus for this course (course code is "BC101") in Richie.

Once this course exists in your richie catalog, its course runs will be synchronized. Does that make sense?

**Comment by sion42x** [comment]
> @sion42x for the synchronization to work, you must first create a syllabus for this course (course code is "BC101") in Richie.
> 
> Once this course exists in your richie catalog, its course runs will be synchronized. Does that make sense?

I assumed that might be the case. Is it expected that there is no "Create Course" module in the Wizard?

![image](https://user-images.githubusercontent.com/82188389/146203699-3f4f0b45-5043-48cd-8358-10bbfeebafb0.png)

**Comment by sampaccoud** [comment]
Ah! You have to be on an organization page to get the course creation wizard. This limitation is planned to be removed but is still in place.

**Comment by sampaccoud** [comment]
Yes and set course dates in OpenEdX largely enough to allow new enrollments on the long run.

**Comment by sion42x** [comment]
Thanks @sampaccoud I appreciate the assistance. I'll update my thread in the tutor discourse as well.

**Comment by sion42x** [comment]
@sampaccoud Two more questions arising from the resolution:

1. How can I then associate a Course with a Category?
2. The search page now errors, and the API for /courses returns a 500. The following error was in the logs:

```
richie_1            | elasticsearch.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', 'script score function must not produce negative scores, but got: [-1.2223565427070353E14]')
```

**Comment by sampaccoud** [comment]
1. Courses are associated to categories from the course detail page, by adding category plugins in the `categories` and `icons` placeholders.
2. Ouch. I need to investigate how a negative score is possible and probably prevent it from happening.

**Comment by sion42x** [comment]
> 1. Courses are associated to categories from the course detail page, by adding category plugins in the `categories` and `icons` placeholders.
> 2. Ouch. I need to investigate how a negative score is possible and probably prevent it from happening. It seems close enough to zero in your case 😅

Thanks on #1, the Category list is coming back blank there too even though I have a published category created. Quite odd.

![image](https://user-images.githubusercontent.com/82188389/146217213-eec57ec9-1f55-4788-b7ec-3ffac054caba.png)

#2, ouch indeed =D I did try reindexing. I'll add more details to the text and see if that makes any difference.

**Comment by sampaccoud** [comment]
1. Was the category created using the page creationg wizard? It seems that you are really missing categories in your project.
2. Did you set the setting `RICHIE_ES_STATE_WEIGHTS`? Bad values in this setting may cause this error.

**Comment by sion42x** [comment]
> * Was the category created using the page creationg wizard? It seems that you are really missing categories in your project.
> * Did you set the setting `RICHIE_ES_STATE_WEIGHTS`? Bad values in this setting may cause this error.

I believe I created it with the wizard, but perhaps I did on the Admin screen? I'll look at that. I did not set the parameter you mentioned, but I'll see if perhaps tutor-richie does.

**Comment by sion42x** [comment]
@sampaccoud I just deleted the category and recreated it while on the Categories page, using the Wizard. 
![image](https://user-images.githubusercontent.com/82188389/146239798-2108eb9a-a904-4bb5-881f-f2ee2a115919.png)

The category does indeed show up properly, and clicking into it provides details:

![image](https://user-images.githubusercontent.com/82188389/146239864-41e20130-8415-4acb-a406-e09fd8cc0b7e.png)

However, /api/v1.0/categories still returns:

```HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "meta": {
        "count": 0,
        "offset": 0,
        "total_count": 0
    },
    "objects": []
}
```

And the list doesn't populate in Django.

**Comment by sampaccoud** [comment]
Actually I think this is normal.
Categories in Richie have a "kind" which are the top categories.
The search endpoint we use is for a kind, not for "categories". You kind look at the queries going out when making a query on the search page.

**Comment by sampaccoud** [comment]
@sion42x It's happening here: https://github.com/openfun/richie/blob/master/src/richie/apps/search/viewsets/categories.py#L40

So what is happening when you call the /api/1.0/categories url is that it filters for the "categories" kind... and you don't get any result...

Maybe it would be cleare to return a 404 in this case. WDYT @mbenadda?

**Comment by sion42x** [comment]
So the /api/v1.0/categories coming back 0 is normal; does that mean it's normal the selector on the Organization/Page wizard returning nothing is also normal?

**Comment by sampaccoud** [comment]
Yes! Meta categories are not proposed as plugins since they are not really categories but "kinds of categories" (e.g. subjects, collections, news and types on https://www.fun-mooc.fr).

The code responsible for this is here: https://github.com/openfun/richie/blob/master/src/richie/apps/courses/models/category.py#L114

**Comment by sion42x** [comment]
> Yes! Meta categories are not proposed for plugins since they are not really categories but "kinds of categories" (e.g. subjects, collections, news and types on https://www.fun-mooc.fr).
> 
> The code responsible for this is here: https://github.com/openfun/richie/blob/master/src/richie/apps/courses/models/category.py#L114

Got it. Once again, you're amazing! I created a category called "Online Learning" and put another category under it, which I was able to attach to a Course and to an Organization. That makes total sense for now.

Now I just need to figure out that elasticsearch issue and I'll be golden. Thanks so much.

**Comment by sampaccoud** [comment]
I managed to get the same error as you and reproduced it in this test: https://github.com/openfun/richie/pull/1545/files#diff-e013ac8c5a758fb0ddee61fdbbce16efb12fe987028cbb0e04d35fdba7916f97R693

It never happened on any of our sites in production but I think it may happen if you set dates very far in the future on your course runs (which is what I suggested you should do :laughing: so that may be your problem!?). So this PR fixes it although I'm not 100% proud of the score computation here :man_shrugging:  https://github.com/openfun/richie/pull/1545

**Comment by mbenadda** [comment]
> @sion42x It's happening here: https://github.com/openfun/richie/blob/master/src/richie/apps/search/viewsets/categories.py#L40
> 
> So what is happening when you call the `/api/1.0/categories` url is that it looks for a top category of kind "categories"... and you don't get any result...
> 
> Maybe it would be cleare to return a 404 in this case. WDYT @mbenadda?

I can catch it here: https://github.com/openfun/richie/blob/master/src/richie/apps/search/viewsets/categories.py#L40. IMO a categories search without a kind is basically a developer error so we could just add a condition for that case.

I think we could even return a `400` with an appropriate error message so we could "guide" new users towards the meta categories. We might want to add a section detailing the use of meta categories in the docs and link to it in our error message as I think this is not intuitive for new users of Richie.

If you agree with this we should create a separate issue.

**Comment by sion42x** [comment]
> It never happened on any of our sites in production but I think it may happen if you set dates very far in the future on your course runs (which is what I suggested you should do 😆 so that may be your problem!?). So PR #1545 fixes it although I'm not 100% proud of the score computation here 🤷‍♂️

Well, I guess I can forgive you this once 😉 

I'll take a look at the PR, thank you! I'll need to sort out how to incorporate it into my implementation of tutor-richie but I feel relieved and my Richie site is beginning to look fantastic!

**Comment by sion42x** [comment]
@sampaccoud I tried running ./sandbox/manage.py bootstrap_elasticsearch manually and received this error:

```
  File "/app/venv/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 172, in _process_bulk_chunk
    raise BulkIndexError("%i document(s) failed to index." % len(errors), errors)
elasticsearch.helpers.errors.BulkIndexError: ('1 document(s) failed to index.', [{'index': {'_index': 'richie_categories_2021-12-15-23h25m23.690737s', '_type': '_doc', '_id': 'L-000300010001', 'status': 400, 'error': {'type': 'illegal_argument_exception', 'reason': 'Contexts are mandatory in context enabled completion field [complete.en]'}, 'data': {'absolute_url': {'en': '/en/categories/online-learning/intro-to-blockchain-and-crypto/'}, 'complete': {'en': ['Intro to Blockchain and Crypto', 'to Blockchain and Crypto', 'Blockchain and Crypto', 'and Crypto', 'Crypto']}, 'description': {'en': '<p>This category focuses on blockchain and crypto basics, including:</p><ul><li>Blockchain</li><li>Wallets</li><li>Smart Contract</li><li>Exchanges</li></ul><p>Content in this category is suitable for all levels of understanding! Blockchain is a complicated topic, but these courses will help you gain a broader understanding of the real concepts behind cryptocurrency and tokens, and how to keep yourself safe on the blockchain.</p>'}, 'icon': {}, 'is_meta': False, 'kind': None, 'logo': {'en': {'src': '/media/filer_public_thumbnails/filer_public/6f/1f/6f1fc16f-84be-4b02-8fcf-a12dc90385c2/android-chrome-512x512.png__500x500_crop-smart_subsampling-2.png', 'srcset': '/media/filer_public_thumbnails/filer_public/6f/1f/6f1fc16f-84be-4b02-8fcf-a12dc90385c2/android-chrome-512x512.png__1000x1000_crop-smart_subsampling-2.png 1000w, /media/filer_public_thumbnails/filer_public/6f/1f/6f1fc16f-84be-4b02-8fcf-a12dc90385c2/android-chrome-512x512.png__2000x2000_crop-smart_subsampling-2.png 2000w', 'sizes': '100vw'}}, 'nb_children': 0, 'path': '000300010001', 'title': {'en': 'Intro to Blockchain and Crypto'}, 'title_raw': {'en': 'Intro to Blockchain and Crypto'}}}}])
```

With the specific part of the error being:
``` ('1 document(s) failed to index.', [{'index': {'_index': 'richie_categories_2021-12-15-23h25m23.690737s', '_type': '_doc', '_id': 'L-000300010001', 'status': 400, 'error': {'type': 'illegal_argument_exception', 'reason': 'Contexts are mandatory in context enabled completion field [complete.en]'},```

I thought perhaps this was due to the course run having no end date, but even providing one gives this error. I saw that 'complete' does look populated there: 'complete': `{'en': ['Intro to Blockchain and Crypto', 'to Blockchain and Crypto', 'Blockchain and Crypto', 'and Crypto', 'Crypto']}`

I can't seem to find a lot of information about this error online.
