### ISSUE TITLE
MySQL error adding homepage section

### ISSUE THREAD

**Issue by sion42x** [openfun/richie#1548]
## Bug Report

**Expected behavior/code**
On a page, adding a Section would put it on your page for editing. 

**Actual Behavior**
A Server Error 500 occurred adding sessions. Logs showed the error was:

```
richie_1            | [pid: 7|app: 0|req: 33/280] 172.18.0.17 () {54 vars in 2232 bytes} [Thu Dec 16 17:45:52 2021] GET /en/static/css/ckeditor.css/ => generated 57335 bytes in 142 msecs (HTTP/1.0 404) 11 headers in 538 bytes (1 switches on core 0)
richie_1            | (1364, "Field 'attributes' doesn't have a default value")
```

**Steps to Reproduce**
1. Create a page (or use one that already exists)
2. Edit the page (?edit at end of URL)
3. Add a Section component
4. Fill in all fields and submit

**Environment**
- Richie version: 2.9.1
- Platform: tutor-richie

**Possible Solution**
This was resolved locally by updating the section_section table in MySQL:

```
mysql> alter table section_section modify column attributes longtext null;
Query OK, 0 rows affected (0.02 sec)
Records: 0  Duplicates: 0  Warnings: 0

mysql> desc section_section;
+------------------+--------------+------+-----+---------+-------+
| Field            | Type         | Null | Key | Default | Extra |
+------------------+--------------+------+-----+---------+-------+
| cmsplugin_ptr_id | int(11)      | NO   | PRI | NULL    |       |
| title            | varchar(255) | YES  |     | NULL    |       |
| template         | varchar(150) | NO   |     | NULL    |       |
| attributes       | longtext     | YES  |     | NULL    |       |
+------------------+--------------+------+-----+---------+-------+
```

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by sampaccoud** [comment]
@sion42x Wow this is not how it's done in Django :astonished: You're not supposed to tweak your database directly, unless you're not planning to use the migration framework. It's most probably a configuration issue in https://github.com/overhangio/tutor-richie.
But I will try to reproduce this problem in richie and propose a solution.

**Comment by sion42x** [comment]
> @sion42x Wow this is not how it's done in Django 😲 You're not supposed to tweak your database directly, unless you're not planning to use the migration framework. It's most probably a configuration issue in https://github.com/overhangio/tutor-richie. But I will try to reproduce this problem in richie and propose a solution.

Understood: please no one do what I did above. I do not know the proper procedure for doing things in Django. 

If I can figure out how to use the migration framework to do it properly I will.

**Comment by sion42x** [comment]
I believe that you nailed the issue @sampaccoud. The tutor-richie Dockerfile does run makemigrations and migrate, so when I upgraded to 2.9.1 it SHOULD have added the features. However, I had the same issue with course run migrations and thought something must have been missed. I had to bash into the Docker container (`tutor local run richie bash`) and run this to fix it:

```
openedx@51181737b595:~/richie/sandbox$ python ./manage.py makemigrations
Migrations for 'courses':
  /app/richie/src/richie/apps/courses/migrations/0033_auto_20211220_0153.py
    - Remove field enrollment_count from courserun
    - Alter field effort on course
Migrations for 'glimpse':
  /app/richie/src/richie/plugins/glimpse/migrations/0004_alter_glimpse_variant.py
    - Alter field variant on glimpse
Migrations for 'section':
  /app/richie/src/richie/plugins/section/migrations/0007_remove_section_attributes.py
    - Remove field attributes from section
openedx@51181737b595:~/richie/sandbox$ python ./manage.py migrate
System check identified some issues:

WARNINGS:
?: (dockerflow.health.W001) Unapplied migration courses.0033_auto_20211220_0153
?: (dockerflow.health.W001) Unapplied migration glimpse.0004_alter_glimpse_variant
?: (dockerflow.health.W001) Unapplied migration section.0007_remove_section_attributes
Operations to perform:
  Apply all migrations: admin, auth, cms, contenttypes, courses, djangocms_googlemap, djangocms_link, djangocms_picture, djangocms_text_ckeditor, djangocms_video, easy_thumbnails, filer, glimpse, html_sitemap, large_banner, lti_consumer, menus, nesteditem, plain_text, section, sessions, simple_text_ckeditor, sites, social_django
Running migrations:
  Applying courses.0033_auto_20211220_0153... OK
  Applying glimpse.0004_alter_glimpse_variant... OK
  Applying section.0007_remove_section_attributes... OK
```

**Comment by sampaccoud** [comment]
I'm on holidays but can you open an issue to @regisb on tutor-richie? Running migrations in the Dockerfile is a bad idea imo. I don't even know how can the production db be connected when you're building the Docker image? 🤯  In Richie we handcraft migrations to ensure smooth migrations between minor versions and delay breaking changes for the next major release. This will be broken by the current installation in tutor-richie.

@regisb I would strongly recommand not running Richie in Tutor. The preferred way to run Richie is classic Django as demonstrated in https://github.com/openfun/richie-site-factory. The Tutor plugin should take care of the openedx side. Both applications can be connected by configuration.

**Comment by sion42x** [comment]
> I'm on holidays but can you open an issue to @regisb on tutor-richie? Running migrations in the Dockerfile is a bad idea imo. I don't even know how can the production db be connected when you're building the Docker image? 🤯 In Richie we handcraft migrations to ensure smooth migrations between minor versions and delay breaking changes for the next major release. This will be broken by the current installation in tutor-richie.
> 
> @regisb I would strongly recommand not running Richie in Tutor. The preferred way to run Richie is classic Django as demonstrated in https://github.com/openfun/richie-site-factory. The Tutor plugin should take care of the openedx side. Both applications can be connected by configuration.

Sure, I will submit an issue there. And I may be totally wrong on how it's being done in Docker, but I'm going based on what I saw last time I ran 'tutor local quickstart' to build richie in. Richie in this case is a plugin of Tutor, and is run in its own container alongside all of the OpenEDX, MFE, MySQL, ES, etc. containers.
