### ISSUE TITLE
Which files/folders to backup in order to be able to migrate docker deployment to another server?

### ISSUE THREAD

**Issue by joerango** [openfun/richie#1550]
**Topic**
Docker setup, Backup, Maintenance

**Question**
I am new to Richie. I started using the docker deployment to experiment with hosting a couple of online courses and I would like to keep a backup of whatever data I create in Richie. My goal is to be able to restore it to another server if it's ever needed. 

I am not a docker-compose expert but as far as I can tell, the only volumes being mounted are from /data. Does that include everything that is persisted to disk by the postgres, mysql, elasticsearch containers? Is it sufficient to backup everything under the /data directory?

**Comment by sampaccoud** [comment]
Yes! And inside the /data directory, only the /media directory is related to what you created. Files in the static directory are collected from the source code.
You also need to backup your database, either postgresql or mysql depending on which one you chose. It's either one, not both. 
Everything indexed in Elasticsearch comes from postgresql (resp. Mysql) and can be recreated at anytime by running the `bootstrap_elasticsearch` command.
