### ISSUE TITLE
Linking to frontend learning MFE in Maple

### ISSUE THREAD

**Issue by sion42x** [openfun/richie#1551]
## Feature Request

In Maple it’s recommended to use the new MFE frontend for courses. Richie sync in 2.9.1 requires the legacy course page as resource link to determine enrollment status, and also to link to the course. 

**Describe the solution you'd like**
Navigating to a course from Richie should go to the new front end (as used by the OpenEDX dashboard). Ideally a new prop would be added: resource link (for API) and destination link (for clicks). 

**Describe alternatives you've considered**
I’ve tried finding a way to just auto redirect legacy course pages to the new MFE but have not been able to. 

**Discovery, Documentation, Adoption, Migration Strategy**
Not sure. 

**Do you want to work on it through a Pull Request?**
I don’t really know how to do it the proper way.

**Comment by sampaccoud** [comment]
@sion42x But we already have different urls for about page and API page. We extract the course id from the resource link in the LMS backend: https://github.com/openfun/richie/blob/master/src/richie/apps/courses/lms/edx.py#L61

So I think we could just write a new backend for Maple with an adapted extraction method...

**Comment by sion42x** [comment]
> @sion42x But we already have different urls for about page and API page. We extract the course id from the resource link in the LMS backend: https://github.com/openfun/richie/blob/master/src/richie/apps/courses/lms/edx.py#L61
> 
> So I think we could just write a new backend for Maple with an adapted extraction method...

Thanks, I should have known you already had a solution. Here's an example of the different links (using latest tutor running maple):

Legacy (no longer supported): https://lms.edunomic.academy/courses/course-v1:Edunomic+BC102+2021_Q4/course/

New (learning frontend MFE): https://apps.lms.edunomic.academy/learning/course/course-v1:Edunomic+BC102+2021_Q4/home (this link won't work right now as I downgraded to Lilac after running into this issue)

When on an upgrade/fresh install of Tutor with Maple, the 2nd link style will be the default and the dashboard will also point to it by default.

**Comment by sampaccoud** [comment]
So if the API endpoint did not change, you should just have to change the regexes in your [LMS backends setting](https://github.com/openfun/richie/blob/master/sandbox/settings.py#L277).

Something like this:
```
RICHIE_LMS_BACKENDS = [
        {
            "BASE_URL": "https://apps.lms.edunomic.academy",
            # Django backend
            "BACKEND": "richie.apps.courses.lms.edx.EdXLMSBackend",
            "COURSE_REGEX": r"^.*/learning/course/(?P<course_id>.*)/home/?$",
            # React frontend
            "JS_BACKEND": "base",
            "JS_COURSE_REGEX": r"^.*/learning/course/(.*)/home/?$"),
            # Course runs synchronization
            "COURSE_RUN_SYNC_NO_UPDATE_FIELDS": [],
            "DEFAULT_COURSE_RUN_SYNC_MODE": "sync_to_public",
        }
    ]
```

If you confirm the solution, @regisb can make it work by default in the next version due early next year.

**Comment by sion42x** [comment]
I'm trying to sort out how to do that, and if sandbox/settings.py is the correct place to look I found that this is the current setting:

```
    RICHIE_LMS_BACKENDS = [
        {
            "BASE_URL": "http://localhost:8073",
            "BACKEND": "richie.apps.courses.lms.edx.EdXLMSBackend",
            "COURSE_REGEX": r"^.*/courses/(?P<course_id>.*)/course/?$",
            "JS_BACKEND": "base",
            "JS_COURSE_REGEX": r"^.*/courses/(.*)/course/?$",
        }
    ]
```

The BASE_URL is set that way I'd assume to work over the docker container. I wonder if that could be why logins/enrollment status sync properly but course enrollments fail per my other issue (https://github.com/openfun/richie/issues/1547)

**Comment by sion42x** [comment]
I don't think that worked, the following error occurred:

```
cms_1                        | 2021-12-29 02:49:30,839 ERROR 8 [richie.sync] [user 6] [ip 72.218.28.34] sync.py:67 - Could not synchronize course course-v1:Edunomic+BC102+2021_Q4 with Richie. Response: {"resource_link":["No LMS configuration found for this resource link."]}
```

I'm assuming that means the new URL is display only, the old URL (`/courses/(.*)/course/`) is still required for the API?

**Comment by sion42x** [comment]
I'm thinking this may be an OpenEDX issue more than a Richie issue. It looks like it links properly to the learning frontend when not a superuser. I'll inquire elsewhere and close this issue for now.

**Comment by sampaccoud** [comment]
Your resource links must match the regex, this is how Richie knows what LMS blackend to use. The error is telling you that your resource link does not match any regex in RICHIE_LMS_BACKENDS.

**Comment by sion42x** [comment]
> Your resource links must match the regex, this is how Richie knows what LMS blackend to use for a given course run. The error is telling you that your resource link does not match any regex in RICHIE_LMS_BACKENDS.

It should have from what I can tell. That said, I'll play with it. It's possible that it's a non-issue anyways because I found that non-superusers have no issues with forwarding to the right location.
