### ISSUE TITLE
(frontend) get r-color from any pallete

### ISSUE THREAD

**Issue by sandroscosta** [openfun/richie#1553]
## Feature Request

As a way to extend a theme color palette, `r-color` should allow for a pallete to be injected into the function. If there's no pallete, it fetches the color from the default `$pallete`;

When heavily modifying theme colors, the default colors sometimes breaks. This happens when updating through versions of richie as well.

## Proposed solution(s)

This could either be achieved by tweaking the existing `r-color` function:

```SCSS
@function r-color($name, $pal: ()) {
  @if $pal != () {
    @return map-get($pal, $name);    
  }

  @return map-get($palette, $name);
}
```

Or by simply merging `$pallete` with the theme one.

**Comment by igobranco** [comment]
@sandroscosta  I think that the PR #1540 would fix this.

**Comment by sandroscosta** [comment]
@igobranco Just read it. It does. I still feel that `r-color` should be a bit more flexible, but i'm going to wait for the merge and the next release.

**Comment by sampaccoud** [comment]
@sandroscosta PR https://github.com/openfun/richie/pull/1540 was merged this morning. Why wait for a release? Better package all this css refactoring in the next release?

**Comment by sandroscosta** [comment]
@igobranco @sampaccoud I think it's something to talk about in the next meeting. PR #1540 will solve most of the questions presented in this issue. Will try to complement the documentation.
