### ISSUE TITLE
Move course run enroll button to the contact block

### ISSUE THREAD

**Issue by igobranco** [openfun/richie#1612]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
Change the course detail template to be equal than the fun-mooc.
On fun-mooc site it is given much more visibility to the current open for enrollment course run button, because it was customized to be on the contact django block.
I've done exactly the same thing for nau.edu.pt.
So I think we should make this the default case for Richie.

**Describe the solution you'd like**
I've copy paste the fun-mooc `course_detail.html` that change the blocks `contact` and `runs_open`.

**Describe alternatives you've considered**
Add same information bellow the enrollment count, but I think the fun-mooc's version is better. 

**Discovery, Documentation, Adoption, Migration Strategy**
If we decide to go further this change, we need to document it on the UPGRADE.md, because the django blocks on the `course_detail.html` could be used to customize the UI.

**Do you want to work on it through a Pull Request?**
If we approve this ideia, I could send a PR.

FUN-MOOC version:
![image](https://user-images.githubusercontent.com/67018/155501008-5a2adc4b-e47b-4ac9-a3af-8be63d307baf.png)

NAU version:
![image](https://user-images.githubusercontent.com/67018/155501074-7871f97b-d92d-4a29-a100-28ef3310859c.png)

Demo version:
![image](https://user-images.githubusercontent.com/67018/155501476-3774b11c-fa42-48ab-a645-42903ba55e00.png)

**Comment by sampaccoud** [comment]
+1
