### ISSUE TITLE
Can't re-login after a logout

### ISSUE THREAD

**Issue by igobranco** [openfun/richie#1667]
## Bug Report

**Problem**
For a Richie site that is connected to an Open edX Juniper release instance.

When a user logouts of the platform and then logs in again, the user couldn't see on Richie site that it is logged in on the Open edX, the top right menu isn't showing the username, dashboard link, etc., and the user can't enroll on any course.

The solution, in a user perspective, is to restart the browser.

On Richie site, an authenticated Open edX user, logout and the widget switches from this state:
![image](https://user-images.githubusercontent.com/67018/161292245-357787d8-4869-4bac-a683-84faa44ede32.png)

To:
![image](https://user-images.githubusercontent.com/67018/161292296-bb49b781-3b11-4938-93b9-7e92dc633b63.png)

If the user wants to re-login, he would click on _LOG IN_ link, after he logins on the Open edX, he would be redirected again to the Richie site, but he won't see this username on the header. For him it is like that the login didn't work.
If the goes to a course page and tries to enroll on a course run, he will continue to see the _Log in to enroll_ button, and he would continue on the same page after clicking on that button.

The problem is resolved if, on Chrome Dev Tools, the developer deletes `RICHIE_PERSISTED_QUERIES` on the browser _Session Storage_ and then re-clicks on login button or if he refreshes the browser.

**Steps to Reproduce**
1. Create a [NAU](https://www.nau.edu.pt/) account / login
2. Go to homepage www.nau.edu.pt
3. View that the Log in button didn't change to the username
4. If we click on it the page is refreshed and the sees the same information

**Environment**
- Richie version:
- Platform:

**Possible Solution**
Possible work around can be to remove or lowers the ttl of the frontend cache.

**Comment by jbpenrath** [comment]
Thank you @igobranco for your issue. The `BaseSessionProvider` do not clear the session storage before the redirect on login or register page and the `queryClient.clear()` do not have sufficient time before the redirect to be persisted by the react query client persistor.
