### ISSUE TITLE
Simple text input doesn't allow links to set target

### ISSUE THREAD

**Issue by sandroscosta** [openfun/richie#1764]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
When adding a simple text widget a course page, the only options available to create a link are the ones described in the image:
![Screenshot from 2022-08-17 10-42-30](https://user-images.githubusercontent.com/34194007/186388553-381dccec-2c78-48c6-b333-8c7671666583.png)

Richie doesn't allow us to define a link target inside a simple text widget.

**Describe the solution you'd like**
Links should allow us to set a target, like other link widgets available on Richie. Links with `target="_blank"` should be set in context. The default would continue to open the link on the same window.

**Do you want to work on it through a Pull Request?**
Yes

**Comment by sampaccoud** [comment]
@sandroscosta so this could be a question of configuration of CKEditor?

**Comment by sandroscosta** [comment]
I haven't invested enough time looking into a possible solution, but would say this is related with CKEditor. If it is something we can just "switch on", it might be an easy fix.

**Comment by igobranco** [comment]
It is related with the CKEditor, the  `RICHIE_SIMPLETEXT_CONFIGURATION` uses the `CKEDITOR_LIMITED_CONFIGURATION` or `CKEDITOR_BASIC_CONFIGURATION` for the course fields. Only the `maincontent` uses the default `CKEDITOR_SETTINGS`.
So, if we try to edit the main content on, for example, the homepage it's possible to edit the link and change the target.
![image](https://user-images.githubusercontent.com/67018/187550877-ceecd49c-6a98-4224-9095-58b4c7d942b1.png)
![image](https://user-images.githubusercontent.com/67018/187550903-78d38755-cf51-464f-be52-fb00177626d8.png)
