### ISSUE TITLE
Create a LMS Handler to recognize course runs managed by Joanie

### ISSUE THREAD

**Issue by carofun** [openfun/richie#1807]
Joanie will be able to synchronize its course runs with Richie.
So Richie must be able to distinguish CourseRun managed by Joanie to other course runs. To achieve that, we have to develop a new lms handler able to parse resource link to recognise Joanie Course Runs.

Resource link of course runs managed by Joanie will correspond to the api route to retrieve course run details.
e.g: `https://joanie.endpoint/api/course-runs/<COURSE_RUN_UUID>/`

**Comment by jbpenrath** [comment]
Closed by #1815
