### ISSUE TITLE
Have the possibility to display an error message that comes from the backend

### ISSUE THREAD

**Issue by sandroscosta** [openfun/richie#1871]
## Feature Request

**Current behavior**
The system returns a generic error message if the system errors out.
```javascript
{step === Step.ENROLLMENT_FAILED ? (
    <div className="course-run-enrollment__errortext">
       <FormattedMessage {...messages.enrollmentFailed} />
     </div>
) : null}
```
The message output is as follows *Your enrollment request failed.*.
We need to be able to provide better feedback to the user. If the user doesn't have privileges to enroll, he should get a clear message about what went wrong.

**Possible workaround**
On our Open edX instance, we added the possibility to return a payload message (already translated to the language defined by the user). 

> Example: The user is now allowed to enroll because the course is restricted only to members of a specific organization.
> The system returns a 400 status with a `you are not allowed to enroll in this course`.

If we can get something like:
```javascript
{step === Step.ENROLLMENT_FAILED ? (
    <div className="course-run-enrollment__errortext">
       { error?.message ?  <p>{error.message}</p> : <FormattedMessage {...messages.enrollmentFailed} />}
     </div>
) : null}
```

**Issues and Questions**
We have done some exploration exercises. As the system is as complex as is, we need to:

- Find a way to mock a request with status 400 and a payload message
- Get that error message back to the user if it exists
- Guarantee everything is backwards compatible

**Comment by jbpenrath** [comment]
Hi @sandroscosta, if you have customized your Open edX instance to return explicit error messages, I think you should first create a custom LMS Api interface to customize enrollment api methods to parse error payload to extract message if needed.

Then as you suggest in your comment we will have to refactor the `CourseRunEnrollment` component to display an error message if one is provided and otherwise display a default error message.

**Comment by sandroscosta** [comment]
@jbpenrath I've taken a closer look to this and have a question. At the moment, when you set the enrollment, you return a `isEnrolled`that is either true of false. 

```javascript
set: async (url: string, user: User): Promise<boolean> => {
        const courseId = extractCourseIdFromUrl(url);
        /*
            edx_csrf_token cookie is set through a SET_COOKIE header send from a previous request
            e.g: To be able to enroll user, you have to get the enrollment before
          */
        const csrfToken = Cookies.get(EDX_CSRF_TOKEN_COOKIE_NAME) || '';

        const isEnrolled = await fetch(ROUTES.enrollment.set, {
          method: 'POST',
          credentials: 'include',
          headers: {
            'Content-Type': 'application/json',
            'X-CSRFTOKEN': csrfToken,
          },
          body: JSON.stringify({
            user: user.username,
            course_details: {
              course_id: courseId,
            },
          }),
        })
          .then((response) => {
            if (response.ok) return response.json();
            if (response.status >= 500) {
              // Send server errors to sentry
              handle(new Error(`[SET - Enrollment] > ${response.status} - ${response.statusText}`));
            }
            throw new HttpError(response.status, response.statusText);
          })
          .then(({ is_active }) => is_active);

        return isEnrolled;
      },
```

In our case, we want to return it as well, coupled with a message, if it is on the payload. This will force us to change this method's return to something like `{inEnrolled, message}`, because Richie doesn't handle these errors, it sends them to Sentry.

Does this make sense?
