### ISSUE TITLE
Frontend - Refactor file structure

### ISSUE THREAD

**Issue by jbpenrath** [openfun/richie#1919]
## Purpose
The frontend codebase aims to grows quickly so we need to reorganise folder structure to ease navigation within the project.

https://github.com/openfun/richie/pull/1703

## Proposal
As a first approach I suggest to use the following structure:

```
frontend/
    ├── scss/
    ├── i18n/
    ├── jest/
    │   └── setup.ts
    └── js
        ├── api/
        ├── components/
        ├── hooks/
        ├── providers/
        ├── translations/
        ├── types/
        ├── utils/
        ├── views/
        │   ├── CourseProductsList/
        │   │   ├── components/
        │   │   ├── hooks/
        │   │   ├── providers/
        │   │   ├── types/
        │   │   ├── utils/
        │   │   ├── index.spec.tsx
        │   │   └── index.tsx
        │   ├── CourseRunEnrollment/
        │   ├── LanguageSelector/
        │   ├── LtiConsumer/
        │   ├── RootSearchSuggestField/
        │   ├── Search/
        │   ├── SearchSuggestField/
        │   ├── UserLogin/
        │   ├── index.spec.tsx
        │   └── index.tsx
        ├── index.tsx
        └── settings.ts
```

The most important folder is the `views` folder where we can found all widgets.
Then I suggest to organize modules as follow :
```
api/
components/
hooks/
providers/
types/
utils/
```

Then the idea is to move shared code to the root of `js` directory and put specific code within the related view directory.
So this folder structure above aims to be used at the root of `js` directory and also within a `view` directory.

**Comment by NathanVss** [comment]
I like the idea, I would mention that `providers/` is maybe no that much used to justify its existence on the root of the folders hierarchy. I would put any provider inside `components/` IMO.

**Comment by rlecellier** [comment]
I think that we could start by create the `/views` directory and then  plan a global reorganisation.

From previous project i propose some adds: 

```
└── js
    |   # this directory help to organise
    |   # the "utils" directory by removing
    |   # what's specifique to each section 
    |   # of the app  
    ├── core/
    |   ├── course/
    |   |   ├── constants.ts
    |   |   ├── types.ts
    |   |   ├── validate.ts
    |   |   └── etc
    |   └── same for all models
    ├── api/
    |   ├── hooks/
    |   |   └── useResources/
    │   └── joanie/
    |       |   # generated api client
    │       ├── gen/
    │       ├── hooks/
    │       |   ├── useJoanieCourse/
    │       |   └── use.../
    │       └── index.ts
    |   # design component, highly reusable
    |   # link, button, input, modal, dropdown...
    ├── ui-kit/
    |   # reused components
    ├── components/
    ├── router/
    |   ├── hooks/
    |   |   └── useDashboardRouter.tsx
    |   ├── dashboardRoutes.ts
    |   └── index.ts
```

**Comment by jbpenrath** [comment]
A resume of our discussions. Mainly new components will be Dashboard pages. We decided to choose the term `pages` to stick with the Next syntax.

So we suggest to split the original `views` folder into three folders : 
```
└── js
    ├── components/
    ├── pages/
    └── widgets/
```
