### ISSUE TITLE
Richie course page: change order of info and simplify date presentation

### ISSUE THREAD

**Issue by igobranco** [openfun/richie#1969]
## Feature Request

We believe that the course page can be improved, to prevent cases where the student don’t understand how much effort and the duration of the course. We have found cases, on support and comments on the social networks, where they simply don’t understand because they view longer start and end dates and they though that the course is very long, but in the reality the course is only a couple of hours in self pace mode. The majority of NAU courses is self pace and I think this situation is more dramatic in our case than in FUN installation, where there are a more balanced mix of self pace and instructor pace. That is why we propose the next improvement on Richie, if we don’t agree we could add it only on our installation, but if we agree on a compromise we could improve the platform for everyone.

### Restrictions
For:
- self pace course
- single open to enroll course run
- current date is in the enrollment period - course in open for enroll

Then on the course run block:
- do not show any enrollment dates.
- show only the end date - on a compact style.

### Language

I think another problem is the language per course run. It is a good feature to have different runs using different languages, but in reality almost all course runs for the course has the same language(s).
What we propose is if all course runs for the course has the same language(s) then we should present that information only once. For an example where a run is almost finish and another is starting up.
One location for this single language presentation could be after the duration, effort and pace; but before the enrollment count.
So, the course languages should be an union of all course run languages.

### Change order of Catch phrase, duration, effort and pace

If we compare Richie with other Course catalog systems, like [edx.org](http://edx.org/) or Coursera, we see that the catch phrase is right below the course title. Only after the catch phrase, it has more information, for example it shows the course duration, effort and pace. We believe that we should change the order of the information to be similar to those platforms.

We propose that we change the order of those elements in Richie. To be like: course title, catch phrase, duration, effort, pace, languages and enrollment count. Maintaining the duration, effort and pace on the same line.

<Course Title>
<catch phrase>
<duration> <effort> <pace>
<languages>
<enrollment count>

### Screen captures and Mockups

Current course presentation from the demo site:
![image](https://user-images.githubusercontent.com/67018/233979535-49b99d71-5179-401c-bf24-edcd5f3db091.png)

(Mockup) The same demo course presented with the suggestion changes:
![course_page](https://user-images.githubusercontent.com/67018/234645064-f393f292-875c-496d-8ff4-ca5890f4b88e.png)

On NAU this change would have this effect:
![nau_course_card](https://user-images.githubusercontent.com/67018/234645208-363e1590-0bb0-4065-a322-52692ce0e50c.png)

**Describe alternatives you've considered**
Implement part on NAU Richie site factory

**Do you want to work on it through a Pull Request?**
Yes.

**Comment by igobranco** [comment]
During today's meeting we have decided to remove the proposal of "Start today", but still preserve the "Ends at ..." before the enroll button.
The decision on remove "Start today" or Start now" is that is irrelevant to the user. The primary action button already has the string "Enroll now" (when the user is authenticated).

We have discussed if we could also remove the "Ends at...", but because there isn't a system validation of the effort/duration with the enrollment end date and the course end date, then it was decided to not to try to hide it.
Ideally it could be used the effort/8hours per day to an reference when we should show the "Ends at..." message, but it also need to have in account the django-cms cache dates. It start to be too effort to implement.
It was decided than in future this information could be presented dynamically using a React component, or improve the existing Course Enrollment React component to show dynamically this single course end date.

### Languages
The languages should be presented in the main content everytime there is at least 1 course run with a language.
Its value should be an union of all course run languages.
On the course run, the language shouldn't be presented if all course runs has the same configured languages.
For example, if all runs at in french then that information shouldn't be shown on the run.
Another example, if there are 2 runs one in French and another in Portuguese, then each run should present its language and the course should present _French and portuguese_. 

### Mockups
I've updated the mockups.

**Comment by igobranco** [comment]
An additional comment about the implementation. We should add a custom class CSS style for the "Ends at <course enrollment date>". So we could completely hide it if we want. On NAU the support team and operators are always reviewing the course/enrollment dates, so I think we could completely hide it.

**Comment by igobranco** [comment]
How about this icons for the number of enrollments and the languages of the course?
- https://fontawesome.com/icons/people-group?f=classic&s=solid
- https://fontawesome.com/icons/globe?f=classic&s=solid

**Comment by jbpenrath** [comment]
To keep homogeneity, we should use outlined icon.
<img width="561" alt="image" src="https://github.com/openfun/richie/assets/9265241/584dc992-451e-4535-9c5b-58d7192c8712">
