### ISSUE TITLE
Change course cards for self pace courses and open for enroll

### ISSUE THREAD

**Issue by igobranco** [openfun/richie#1970]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
The course card footer isn't relevant for self pace courses that are open for enrollment and in progress.

**Describe the solution you'd like**
Currently on NAU we aren’t showing the course card footer, because for the our “normal” courses - self pace and open for enrollment and in-progress is showing irrelevant information, that is why we have decided to not show for any course. But there is some cases that the footer is relevant, like when the course is going to start in a couple of days, is archived, etc.

We propose the following change on the course cards:
If the course is:
- open for enrollment;
- it has enrollment start and end defined - not null;
- a the course run has started

then:
- replace the text in the card footer with _Open for enrollment_

Warning: if a course doesn't have a course end date, but has an enrollment end date, it is being shown on Richie as "On-going" on the course card footer. The current behavior should be preserved.

**Describe alternatives you've considered**
Any.

**Discovery, Documentation, Adoption, Migration Strategy**
Mockup:
![image](https://user-images.githubusercontent.com/67018/234652083-416a1e61-6b39-4ee8-b4fa-dc631c0589ce.png)

**Do you want to work on it through a Pull Request?**
Yes.

**Comment by igobranco** [comment]
During the 2023-04-26 meeting it was decided that this change should be implemented for all courses and not only for the self pace courses.
Nevertheless the "On-going" text should be preserved.
The issue description has been updated.

**Comment by jamoqs** [comment]
At now, i'm working on it.
