### ISSUE TITLE
Users are unable to access course via course_page after enrollment ends

### ISSUE THREAD

**Issue by sandroscosta** [openfun/richie#1981]
## Issue
When a course that you've enrolled in reaches the end of its enrollment date, the button to `Go to course` disappears. This confuses users into thinking that they do not have access to the course anymore.

### Scenario 1
The course is open for enrollment. The course itself ends after the enrollment end date.
I'm enrolled in this course run and I have a button that I can use to go to course.
![Screenshot from 2023-05-17 11-29-07](https://github.com/openfun/richie/assets/34194007/ae7c9db2-e799-48fd-9f3d-419dc24be811)

### Scenario 2
The course is closed for enrollment. It's set as **Ongoing**. I'm still enrolled in the course.
The **Go to course** button disappears as the course run moves to the **Ongoing** section.
![Screenshot from 2023-05-17 11-29-39](https://github.com/openfun/richie/assets/34194007/c9c4dabf-3a45-4678-afc8-5eaf88b77dba)

The problem doesn't seem to be due to the day the button is implemented in React. The button is never rendered again as the course going into the "Ongoing" section.

## Feature Request
Add a check to see if the user is enrolled and display the `Go to course` button while the course is available.

**Possible solution**
Add an if clause to check if the user is enrolled and if he is, render the `fragment_course_run.html`

**Do you want to work on it through a Pull Request?**
Yes

**Comment by jbpenrath** [comment]
@NathanVss Here it is the propal to address this issue.
<img width="406" alt="image" src="https://github.com/openfun/richie/assets/9265241/35fb171e-0657-40b6-84f6-e5267ea08794">
