### ISSUE TITLE
CMS Template not taking into account ONGOING_CLOSED course runs

### ISSUE THREAD

**Issue by NathanVss** [openfun/richie#2016]
## Bug Report

**Problematic Behavior**
During the reactify of the course runs on the syllabus I realized on the following line:

https://github.com/openfun/richie/blob/d9c1102dbec05ccbd6522e009018f5a9081a7379/src/richie/apps/courses/templates/courses/cms/course_detail.html#L359

That the `runs_dict.5` is not taken into account, while it is below here:

https://github.com/openfun/richie/blob/d9c1102dbec05ccbd6522e009018f5a9081a7379/src/richie/apps/courses/templates/courses/cms/course_detail.html#L411

This could lead to having:
"No course runs"
And later having a `ONGOING_CLOSED` course run displayed.

**Expected behavior/code**

We shall never have "No course runs" and a `ONGOING_CLOSED` course run displayed at the same time.

**Environment**
- Richie version: *
- Platform: *

**Possible Solution**
Add `runs_dict.5` to the first condition.

**Comment by jbpenrath** [comment]
Fixed #2015
