### ISSUE TITLE
Unenrolling from a course run is not reflected in real-time in the enrollment area

### ISSUE THREAD

**Issue by NamFra** [openfun/richie#2017]
## Bug Report

**Problematic Behavior**
If a user unsubscribes from a course run and tries to re-enroll immediately after, the access button remains active and allows them to access the public `/info` page without being enrolled.

[richie-enrollment-bug.webm](https://github.com/openfun/richie/assets/23249365/5c46cb35-379c-491f-b421-10f27d198475)

This issue seems to be due to a caching problem, as refreshing the page a few minutes later displays the "Enroll Now" button again, which significantly reduces the priority of this bug.

[richie-enrollment-bug-refreshed.webm](https://github.com/openfun/richie/assets/23249365/d152c02c-1b20-4aa6-9c95-ec29793d2499)

**Expected behavior/code**
Ensure that actions are reflected in real-time on the UI and no longer display the access button if the user is unenrolled. 

**Steps to Reproduce**
1. Log in to fun-mooc.fr
2. Enroll in an open course
3. Unenroll from the course from the instructor dashboard
4. Return to the course page
5. Click on the button without being enrolled

**Environment**
- Richie version: 2.22.0 & 
- Platform: Richie FUN MOOC & MOOC Bâtiment Durable

**Possible Solution**
Does this PR https://github.com/openfun/richie/pull/2015 potentially address this issue?

**Comment by jbpenrath** [comment]
Hi @NamFra, this is actually a known issue.
Unfortunately, Richie cannot be aware when a user unerolls from OpenEdX. The only solution could be to disable cache for this kind of request but it implies performance issue so the current state is, from my point of view, the better trade off.

Then, when we will manage CourseRun from Joanie, user will have to unenroll from Richie catalog so the problem will be fixed.

**Comment by NamFra** [comment]
Thank you for your feedback, @jbpenrath. 
I suspected that might be the case. I had started working on the issue before realizing that the unenrollment eventually happens, but I posted it to see if there were any insights, especially regarding the new React front-end for CourseRun. 
But you're right, if the user no longer unenrolls from Open edX, that will solve the problem 👏
