### ISSUE TITLE
Add new placeholders on course detail page (syllabus)

### ISSUE THREAD

**Issue by jsfununivers** [openfun/richie#2087]
**Is your feature request related to a problem or unsupported use case? Please describe.**  
With the new courses (department FormaPro) scheduled to be available on FUN, we are required to include the following information on the course presentation page: **required materials** and **accessibility**

**Describe the solution you'd like** 
Add two new placeholders with simple text plugins: 
- `Required Equipment` / `Matériel requis`(after Prerequisites) 

![image (3)](https://github.com/openfun/richie/assets/138883136/d999e7dc-1f4e-4908-a43c-e5ca2a0af9b7)

-  `Accessibility` / `Accessibilité` (before the course plan)

![image](https://github.com/openfun/richie/assets/138883136/73ae66fc-d353-44e9-b5e5-7ddaed434b1e)

**Describe alternatives you've considered** 
Integrate this information using the additional information section. The problem is that this information would end up at the bottom of the page and these fields could benefit all sites ?  - they will not be displayed if they are not filled in (to be discussed).

**Comment by jbpenrath** [comment]
You should also add RDFa tagging.
`Required material` could be an `about` property of type `Thing` containing a `name` and `description` (Check format placeholder for example).
`Accessibility` could be `accessibilitySummary`
