### ISSUE TITLE
(i18n) fix the translation of the sentence above the programs on the French course pages

### ISSUE THREAD

**Issue by NamFra** [openfun/richie#2125]
## Bug Report

**Problematic Behavior**
The sentences "Ce cours fait partie d'un parcours" or "Ce cours fait partie de parcours" are displayed in English on the course pages in French.

**Environment**
Richie version: 2.24.1

**Possible Solution**
Translations exist but are not displayed. Perhaps this is a bug due to the difference in display depending on whether a course is attached to one or several programs?
https://github.com/openfun/richie/blob/master/src/richie/locale/fr_FR/LC_MESSAGES/django.po#L1401

**Additional context/Screenshots**
This can be seen on this syllabus: https://demo.richie.education/fr/cours/lart-datteindre-vos-buts-en-toute-tranquilite/

![image](https://github.com/openfun/richie/assets/23249365/9c0ff3f2-4b2a-4591-80e0-0f553f5a2203)

**Comment by jbpenrath** [comment]
Should be fixed by #2210
