### ISSUE TITLE
Order detail view sidebar is useless

### ISSUE THREAD

**Issue by NathanVss** [openfun/richie#2160]
## Bug Report

**Problematic Behavior**
This sidebar has no navigation link. So it looks a bit odd.

**Expected behavior/code**
Maybe show the home sidebar even in the order details view.

**Additional context/Screenshots**
<img width="1284" alt="Capture d’écran 2023-12-04 à 11 41 17" src="https://github.com/openfun/richie/assets/9628870/e96f6f99-5e1c-4f9d-8d8f-61bfbf95c073">

**Comment by jbpenrath** [comment]
I'll add a go back link maybe 🤔 

In any case, I'll use the home sidebar here. Indeed, we are displaying the product name to precise the context of the main content then if we display the home sidebar we would lose this context that is weird from my point of view.
