### ISSUE TITLE
Cannot purchase Certificate Product on Enrollment if user already owns an inactive order

### ISSUE THREAD

**Issue by jbpenrath** [openfun/richie#2163]
## Bug Report

**Problematic Behavior**
When a user owns an inactive order (`draft`, `pending`) on a certificate product, the payment failed with the following message : `An order for this product and enrollment/course already exists.`

**Expected behavior/code**
When a user owns a `draft` or `pending` order related to a certificate product it should be able to resubmit this order to try to pay again.

**Resources**

~Blocked by https://github.com/openfun/joanie/issues/504~ (✅ merged)

**Comment by rlecellier** [comment]
Should have been fixed by https://github.com/openfun/richie/pull/2164
