### ISSUE TITLE
🐛 (frontend) hide "go to course" button for unstarted course runs and display the approx. waiting time before the course starts

### ISSUE THREAD

**Issue by NamFra** [openfun/richie#2178]
## Bug Report

**Problematic Behavior**

The 'Go to course' button is now displayed even for course runs that have not started yet.  Users can click on it, which either redirects them to the LMS dashboard with the message 'The course you are looking for does not start until {date}' (in the best scenario), or results in a 500 error.

**Expected behavior/code**
Gray out the 'Go to course' button for standard users, display the enrollment confirmation message, along with the approximative time remaining before the start of the course (https://github.com/openfun/richie/commit/9f5b51a2eb9f233b1d1b7b485966e794479e7adf).

**Steps to Reproduce**

1. Log in to https://studio.richie.education/ as an admin
2. Enter a future course start date on this page: https://studio.richie.education/settings/details/course-v1:edX+DemoX+Demo_Course.
3. Log out from https://studio.richie.education/
4. Log in as a student at https://edx.richie.education/login.
5. From https://demo.richie.education/fr/cours/?availability=coming_soon&limit=21&offset=0, enroll in a course run starting soon
6. The 'Go to course' button is available without mentioning a future start date.

**Environment**
- All Richie platforms (production)

**Possible Solution**

- This commit seems no longer being in use: https://github.com/openfun/richie/commit/9f5b51a2eb9f233b1d1b7b485966e794479e7adf
- It's possible it was removed when the course runs list was ported to React (v2.23.0): https://github.com/openfun/richie/compare/v2.22.0...v2.23.0 ? I haven't identified the specific change yet.
- Other possible leads:
    - https://github.com/openfun/richie/blob/master/src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseRunEnrollment/index.tsx#L312
    - https://github.com/openfun/richie/commits/292da354dc276c85b0a600dc30a23be258b1d1fb/src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseRunEnrollment/index.tsx (commit history)

**Additional context/Screenshots**

[richie-go-to-future-course-runs.webm](https://github.com/openfun/richie/assets/23249365/76eb3b75-5af5-47d8-a5cc-4a8ae0015cd2)

**Comment by NathanVss** [comment]
Hi @NamFra I'm going to investigate this issue. Thank you for giving lots of informations 👌
