### ISSUE TITLE
Multi-site support?

### ISSUE THREAD

**Issue by ormsbee** [openfun/richie#219]
In the meeting today, there was talk of configuration through settings files. Is multi-site support something that is being considered for this project? A use case for this would be to give different companies separately branded portal experiences to access the courses that are relevant for their employees.

**Comment by sampaccoud** [comment]
That's a good question... and the answer is not straightforward. Here are my thoughts on the subject.

## Yes it's multisite

Django-CMS is multisite by default. After creating a second site from the admin (using Django's site contrib) you will able to switch between sites in the page tree view:

![image](https://user-images.githubusercontent.com/1427165/41440936-c6bd8552-7030-11e8-955d-6957d87ead0b.png)

It means that all the content pages can be created on seperate sites (including our custom Organization, Person, Course and Subject pages).

All this is already available today.

## Actually the search is not multisite yet

The search as it is today will not allow multisite. You can declare pages using the search template on separate sites but the mechanism to query separate search indexes was not planned. I think this is not hard to add and we should do it:

- [ ] Create one Elasticsearch index per site when regenerating indexes, the name qof each index should include it site id or domain name,
- [ ] In each index push only the pages corresponding to its site,
- [ ] add a site parameter to the search query API and target only the index for the targeted site.

## Multisite enrollment and payment is tougher

Our mid-term plan is that enrollments and payments should take place directly on the portal. It means that end-users will have a user account on the portal. If we want to add multisite support in this case, the user table as well as other tables will have to be multi-tenant. This is not trivial but may be achievable with [django-tenant-schemas](https://github.com/bernardopires/django-tenant-schemas).

WDYT?

**Comment by mbenadda** [comment]
I'll just add that on the frontend side, multi-site with separate branding can add complexity, as we're already dealing with extensibility and building *properly* a hybrid Django/webpack app.

- for pure CSS theming, it should be straightforward to write X different `main.scss`, run X builds and import the result of those in the templates (using Django CMS features?) but that is out-of-scope for both the Search & Courses+ projects which Richie will be split into
- for JS I think it is pretty far out. Right now the only part that will be really written as JS is the search view, and the filters should be customized through settings — like the CSS, possible to run X builds with X settings file but still out-of-scope for the projects we're working on now

For now I think it's probably way easier to run one instance of the portal for each site (even if they all point to the same edx with micro sites)

**Comment by sampaccoud** [comment]
Closing this issue. We ruled-out multisite as it adds complexity and no clear benefits. We host with Docker, one database per site and building images with a site factory: https://github.com/openfun/richie-site-factory
