### ISSUE TITLE
Frontend - CourseProductItem - Order with submitted state

### ISSUE THREAD

**Issue by jbpenrath** [openfun/richie#2196]
## Bug Report

**Problematic Behavior**
If an Order has a state `submitted`, information displayed is the same as if the state is `validated`.

**Expected behavior/code**
If the backend return an order with a state `submitted`, it should be displayed as `pending`.

**Comment by rlecellier** [comment]
Can you give the page where this happend ? 
Every order status messages should be display using [OrderStateMessages](https://github.com/openfun/richie/blob/master/src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/OrderStateMessage/index.tsx).
This component have a dedicated messages for submitted orders.

**Comment by jbpenrath** [comment]
This is related to the `CourseProductItem` on the syllabus course page.

**Comment by rlecellier** [comment]
pending: remove sign contract alert
submitted: remove sign contract alert
