### ISSUE TITLE
Basic Standard template and look

### ISSUE THREAD

**Issue by 2018D** [openfun/richie#220]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
The basic template and static files in the app are barebone. I'd like to flesh it out so that right out the box we can have a nice portal website. Starting with the course-detail page.

**Describe the solution you'd like**
I'll edit the templates and the static files.
The templates will have limited placeholder to allow anyone to edit on the cms without breaking the webpage's structure. The limited placeholder will make up a form that people fill in.

**Describe alternatives you've considered**
Without the limited placeholder, you would have a lot of difficulty maintaining the same look and feel throughout the whole website, especially if you hand it over to non web designer.

**Discovery, Documentation, Adoption, Migration Strategy**
I'll use {% extends template %} on the plugins to have it as modular as possible. Basic look and feel will be maintained by the django-cms core.

**Do you want to work on it through a Pull Request?**
I'll make a pull request as soon as I'll have the course_detail page working how I want it to.

**Comment by 2018D** [comment]
Seeing that Mehdi is working on the organisation page, i went and focused this issue onto the course-detail page.

**Comment by sveetch** [comment]
Hi @2018D just to let you know i'm working now on the course template to be able to structure and our default content for a Course page.

We will add about ten default content (we retained the ones you added in your branch) almost all with their own placeholder with a basic HTML structure directly using BEM convention (so without bootstrap components).

**Comment by 2018D** [comment]
About the «Course key of active course session» on the side, are you planning on making it into a link towards something? or is it there as information only?
