### ISSUE TITLE
🐛(frontend) useUnionResources reset page scroll

### ISSUE THREAD

**Issue by rlecellier** [openfun/richie#2227]
## Bug Report

**Problematic Behavior**
On the teacher dashboard course listing page.
When all the pages have been fetch, the list switch to the beginning of the page.

**Expected behavior/code**
We should stay at the end of the liste when finishing scrolling bottom.

**Steps to Reproduce**
1. go on the course listing page
2. scroll bottom
3. observe that you get teleporte to the beginig of the page.

**Environment**
- Richie version: 2.25.0-beta.1
- Platform: linux / firefox

**Additional context/Screenshots**
[Capture vidéo du 16-01-2024 16:06:48.webm](https://github.com/openfun/richie/assets/139848/9f12e436-fe6d-4212-9fd8-996027ebcd15)

**Comment by NathanVss** [comment]
I can't find a way to reproduce this bug on MacOS, maybe it is 100% related to your OS 🤔
