### ISSUE TITLE
Frontend - Rename teacher dashboard menu entry

### ISSUE THREAD

**Issue by jbpenrath** [openfun/richie#2244]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
Currently, we name the dashboard dedicated to manage trainings "teacher dashboard". After a demonstration, it appears this term is weird as other user than teacher have to use this dashboard (university members, course leaders...). 
 
**Describe the solution you'd like**
We should rename this entry by something like "Administration dashboard" or "Training dashboard" ?

Furthermore, we could display this entry apart from other to explicitly show this is an extra entry not available to all users.

**Comment by rlecellier** [comment]
We could isolate this menu item at the beginning  of the list like
![main_menyu](https://github.com/openfun/richie/assets/139848/ede04758-89be-4491-8e8e-cfd65d72a367)

**Comment by jbpenrath** [comment]
I'll just put it below instead of above entries

**Comment by rlecellier** [comment]
I wanted to keep logout as the last entry, that's why i proposed it on top.

**Comment by jbpenrath** [comment]
Ok right !
