### ISSUE TITLE
"Load more" remains displayed at the bottom of the list on teacher dashboard

### ISSUE THREAD

**Issue by NathanVss** [openfun/richie#2317]
## Bug Report

**Problematic Behavior**

"Load more" remains displayed at the bottom of the list at `http://localhost:8070/en/dashboard/teacher/courses?query=Course`

<img width="1345" alt="Capture d’écran 2024-03-05 à 10 48 05" src="https://github.com/openfun/richie/assets/9628870/ed239c01-8fd7-49c9-8941-0df967886fcc">

**Expected behavior/code**

It should disappear once the list is fully loaded

**Steps to Reproduce**
1. Go to `http://localhost:8070/en/dashboard/teacher/courses?query=Course`

**Comment by rlecellier** [comment]
A fix may have been found in the linked PR.
But the test that should fail do not. Also, it's no longer possible to reproduce this bug on our development environment.
Let's wait and see if we can catch it again in the future.
:hourglass_flowing_sand:
