### ISSUE TITLE
Download Certificate / Contract does not work

### ISSUE THREAD

**Issue by jbpenrath** [openfun/richie#2336]
## Bug Report

**Problematic Behavior**
Any download button does not work as expected (Certificate PDF, Contracts archive). Indeed a txt file is downloaded. Once download, if I rename the download file to replace txt extension by the expected one, all is working fine.

**Expected behavior/code**
Downloaded file should have the right extension file.

**Steps to Reproduce**
1. Go the Learner dashboard with a learner who earned a certificate
2. Go to certificates view
3. Click on download
4. A txt file is downloaded

1. Go the Administration dashboard with a user able to download organization contracts
2. Go to organization contract view
3. Click on Download contract archive
4. A txt file is downloaded

**Environment**
- Richie version: Canary
- Platform: Mac OS - Chromium

**Comment by rlecellier** [comment]
This is fixed since [eb9145018bafa47ffefcd8a149ac7b0edce97f0e](https://github.com/openfun/richie/commit/eb9145018bafa47ffefcd8a149ac7b0edce97f0e)
