### ISSUE TITLE
Flag as enrolled to On going products

### ISSUE THREAD

**Issue by jbpenrath** [openfun/richie#2361]
## Bug Report

**Problematic Behavior**

On a course syllabus, a course run representing a Joanie product the user has not purchased is suffixed by the badge "Enrolled"

<img width="425" alt="image" src="https://github.com/openfun/richie/assets/9265241/977c77f3-6d0d-40b2-ad37-d39912d58fc5">

**Expected behavior/code**

If the user has not purchased the related product, the badge should not be displayed.
Further tests should be done to check if all is working well with simple course run, product purchased, etc...

**Steps to Reproduce**
1. Create a product with on going course run on Joanie
2. Synchronize the product on Richie
3. BOOM

**Comment by rlecellier** [comment]
I didn't succeed to reproduce and didn't understand who this tag could be displayed without an existing enrollment for the current user.

The tag is displayed in [CourseRunItemWithEnrollment](https://github.com/openfun/richie/blob/master/src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseRunItemWithEnrollment/index.tsx#L43-L48) when `useCourseEnrollment` return `enrollmentIsActive === true`
useCourseEnrollment will fetch an existing enrollment and if one is found, it will then [fetch if its active](https://github.com/openfun/richie/blob/master/src/frontend/js/widgets/SyllabusCourseRunsList/hooks/useCourseEnrollment/index.ts#L24-L35).

The only way to have `enrollmentIsActive === true` is to have an active enrollment in Joanie attached to the resource link of the courseRun.
