### ISSUE TITLE
Add babel to the build process

### ISSUE THREAD

**Issue by mbenadda** [openfun/richie#253]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
The main thrust behind the idea to add `babel` to our process is that we'll need it to use [react-intl extractor](https://github.com/babel/babel-loader). See #89 for more about this.
Side bonuses: we get to use `babel-polyfill` as well as `babel-preset-env`.

**Describe the solution you'd like**
Add babel as a second loader _after_ Typescript for ts/tsx files. Tweak `tsconfig.json` to output ES6 and keep `import` statements intact, while still being able to resolve deps and import JSON.

**Describe alternatives you've considered**
Not use babel, find other solutions for string extraction & i18n. Other solutions were not satisfying and harder to automate.

**Discovery, Documentation, Adoption, Migration Strategy**
No changes to `yarn build` use. We'll need to add some docs on the build.

**Do you want to work on it through a Pull Request?**
Yes.

**Comment by jmaupetit** [comment]
If I understand well, it means that we will have two consecutive code transpilation phases (TS+babel). Don't you think this will make debugging rather complex?

**Comment by mbenadda** [comment]
> Don't you think this will make debugging rather complex?

Source maps are working. Do you have other concerns? How would it make debugging more complex than with just TS?

> Is it worth it? Is this the way to go with TS?

I think it is. Tooling for i18n string extraction is pretty thin on the ground, so if we have a simple, working, automated solution it's definitely worth adding a little bit of complexity to the build config IMO.

**Comment by mbenadda** [comment]
Source maps mean errors, logs, etc. get associated with the actual call site in the TypeScript source. Babel does generate new source maps based on the ones TS generated (otherwise we could not associate the final code to the actual source).

> In this case, babel-related bugs may be hard to track

Because the ES6 babel compiles from is an intermediate representation that does not get written to disk? Indeed, you would have to output the ES6 itself from typescript to take a look at it.

However, I would argue that such bugs would be a rare occurence. Babel is mature (more so than TS I'd say) and I would be amazed if we actually ran into a bug in it when compiling vanilla ES6. Combining TS & babel is not exotic and mostly works out of the box.

---
Bugs in our own code (or regular deps) which would constitute >99% of debugging work will be straightforward to pinpoint with source maps.

**Comment by jmaupetit** [comment]
Thanks for this explanation. I put my trust in you. Let's do this!
