### ISSUE TITLE
Consider distributing sandbox' templates with Richie

### ISSUE THREAD

**Issue by jmaupetit** [openfun/richie#268]
## Purpose

Some templates have been left in the sandbox:

```
sandbox/templates/
├── menu
│   ├── menu.html
│   └── _menu.scss
└── richie
    ├── base.html
    └── fullwidth.html

2 directories, 4 files
```

We should decide whether or not they must be distributed with the Richie Django application.

## Proposal

I would distribute the base & fullwidth templates but not the menu template as it's tightly bounded to
Django-CMS but  not Richie.

In this case, one problem remains: menu styles; our scss build mixes scss in Richie's apps templates directories and the sandbox (doh!).

**Comment by sveetch** [comment]
But sandbox is alike richie demo no ? Considering this, demo template should lives only in the demo if they are not required by some application, except to the base.html template.

If sandbox is indeed the richie demo, it should be documented for users to know they may copy/paste it to start their own site base on richie.

Also, we may maintain a basic starter kit for a new project base on richie with the wonderful [Cookiecutter](https://github.com/audreyr/cookiecutter).

**Comment by jmaupetit** [comment]
Richie's templates use the `richie/base.html` & `richie/fullwidth.html` templates, hence they should be distributed.

> Also, we may maintain a basic starter kit for a new project base on richie with the wonderful Cookiecutter.

+1 for having a Cookiecutter for Richie!

**Comment by jmaupetit** [comment]
Concerning menu styles, yesterday we came with the idea to have a second front-end build for the sandbox.

**Comment by 2018D** [comment]
Any progress on how you're planning on adding menu style?

**Comment by mbenadda** [comment]
What would you need?
We have not worked on this in the past two weeks but as you start your own portal project maybe you can help us understand the requirements better.

**Comment by sampaccoud** [comment]
Closing as there are no more templates in the sandbox. All templates have been moved to the core app.
