### ISSUE TITLE
Add a plugin to define the publishing licenses of a course

### ISSUE THREAD

**Issue by sampaccoud** [openfun/richie#273]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
We need a plugin to define a licenses for:

- the content of a course
- the content created by participants in a course

**Describe the solution you'd like**
To add a license to the course content, the person editing the page can add a "license" plugin and choose from 8 possible licenses in a select box:

- One of the 7 variants of Creative Commons as defined here https://en.wikipedia.org/wiki/Creative_Commons_license#Seven_regularly_used_licenses
- Reserved Rights

A free text input is available for the person to give details (e.g. version of the cc license, adaptated version, etc.).

The license is displayed on the site with the free text and a set of logo+name+description defined by us (in the code) for each of the possible licenses.

**Discovery, Documentation, Adoption, Migration Strategy**
This is what we have today on the site:
![image](https://user-images.githubusercontent.com/1427165/42174775-af0a9b2e-7e23-11e8-9ff7-c634df11d33c.png)

**Comment by sveetch** [comment]
Functionally it's done with PR #324 that has been merged but it lacks of some unitests, factory and to be included in demo-site.

**Comment by sveetch** [comment]
Issue will continue in PR #341 with missing factory and tests
