### ISSUE TITLE
Filter related PageExtension items following page language

### ISSUE THREAD

**Issue by sveetch** [openfun/richie#296]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
Currently we don't bother of languages in manager methods to get PageExtension draft or published items, we just get the PageExtension, no matter the parent is translated in different language from the default one.

I just tested to fill draft and published versions of Organizations in french and it almost works when listed from a Page course in french. 

I mean almost because french version is showed instead of english one when it exist (draft or published) but if an organization item does not exist in french, the english version is showed anyway. I think it should not display.. no ?

**Describe the solution you'd like**
First, ensure we don't want to display PageExtension items from default language when querying from another language. If we want to keep showing the default language items, this is issue can be closed.

If we don't want to display default language items, we have to find a way to filter items depending from current Page language.

**Describe alternatives you've considered**
Keep showing default language items as a fallback when there is no translation available, but it seems troubling for users.

**Discovery, Documentation, Adoption, Migration Strategy**
First we should try to find a query selector to filter from sql schema.

It seems `extended_object__languages` is relevant but it's a comma separated list of language codes (aka `en,fr`) so we will have to make a complex query to perform accurate selection, remember a language code can be something like `fr` or `fr-be`.

Finally we may filter item from a Python loop looking at available language for the item through Page model method like `get_title`. But this will trigger an additional query for each loop item.

**Do you want to work on it through a Pull Request?**
I may be able to make at least some R&D on this.

**Comment by sampaccoud** [comment]
@sveetch can you confirm whether this PR has fullfilled your request or what is still not working as expected:
https://github.com/openfun/richie/pull/304

**Comment by sveetch** [comment]
Closed since #304 has fixed this issue.
