### ISSUE TITLE
Organization list page

### ISSUE THREAD

**Issue by 2018D** [openfun/richie#313]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
I want a page similar to these for the organization list page: 
https://www.fun-mooc.fr/universities/
https://www.edx.org/schools-partners

**Describe the solution you'd like**
Use a version of list-of-child template using course-glimpse style to show the blocks. 

**Discovery, Documentation, Adoption, Migration Strategy**
- [ ] Obtain either logo or banner (both?) data of the child pages to show it on parent page.
- [ ] Complete the layout of the parent organization page.

**Do you want to work on it through a Pull Request?**

I've started on the layout. I will need some pointers to obtain the childs' data.

**Comment by sampaccoud** [comment]
Actually there is a simpler way to do this. I proposed the change here:
https://github.com/openfun/richie/pull/314/commits/819d189f23cadee875ac64c24abcf7d66c64ec6c

You should be able to use the same template tag {% show_placeholder ... %} to build the organization list page.
