### ISSUE TITLE
Course glimpse from course content

### ISSUE THREAD

**Issue by sveetch** [openfun/richie#350]
## Feature Request

While making course glimpses (each course a card object inside a flex grid), i figured some things that not works very well with current course content.

### Course has no image preview

There is only a video teaser, enforced by plugin settings. Video does not work very well inside glimpse, i mean the video is working, but it takes more time to load every video (and i just tested with three items, in real production site case the page loading could be huge). 

Also visually this is not really nice since video preview is often blur because video size is often largely higher than card size.

### Current course session is not really reachable

As already discussed with @sampaccoud there is some algorithm to introduce into a helper in model (or through a template tag) to get the current session object, since we need to display current session name and date in course cards.

However @sampaccoud has offered to implement it in coming commit, this point is here just to remember this issue.

### 'course_syllabus' too long for a glimpse

Since we moved everything to placeholder, i included 'course_syllabus' in course fragment but this has issue since this is content writed in CKEditor so it can be one or more paragraph without any limits on their text size.

Glimpses are some little cards in a grid and having these long syllabus take too much size and does not display very well.

Commonly with some simple text we can use builtin template tags to nicely cut text but this is impossible with placeholder, either we take all the rendered placeholder content or not at all.

And since syllabus is displayed on course detail page i don't think we can stand on user to write very short syllabus with only 6/7 words as we can see it in fun-mooc.fr course cards.

## Describe the solution you'd like
I think we should go back to include some content like image preview and short resume on Course model object instead of the "everything as placeholder".

I don't think image preview has meaning to be displayed on course detail and short resume may conflict with syllabus. Also it could be safer to be able to use builting template tag to ensure the resume never exceed some maximum height inside card. 

## Describe alternatives you've considered
Image preview and short resume could be placeholder, hided with css in course detail page but this will be a very bad and dirty way in my opinion. 

## Screenshots

**Current course card from fun-mooc.fr**

![funmooc-card](https://user-images.githubusercontent.com/1572165/45255570-81d5d980-b388-11e8-8e3c-e235414a4774.png)

**On work course card from richie**
Not finished but give an idea of related problems.

![onwork-card](https://user-images.githubusercontent.com/1572165/45255571-91edb900-b388-11e8-84c9-cb2f82573a81.png)

**Comment by sveetch** [comment]
@sampaccoud syllabus are free HTML content, mostly paragraphs and i don't think you can correctly truncate this. There is https://docs.djangoproject.com/en/2.1/ref/templates/builtins/#truncatechars-html but the example is about only one paragraph, not sure how it will work with two or more paragraphs.

For the image preview displayed only in draft, well yeah it's "smart", but as you said it also it's tricky :) I'm not very confident about, in my opinions the draft should reflect what will be showed in published version, not to include additional information that will go elsewhere.

We have to take a little more time to think about these solutions.

**Comment by sveetch** [comment]
So with more discussion about this, we finally choose to add image preview as a placeholder that will show only in draft mode (with conditional "if" blocks around placeholder) that have to be showed as a preview. No short resume text to add since, in fact, course glimpse card don't have to show a resume, i was wrong because it's just the organization name.

**Comment by sampaccoud** [comment]
@sveetch I have the feeling this issue is now fixed can you confirm?

**Comment by sveetch** [comment]
You are right, closing it
