### ISSUE TITLE
Add a course plugin

### ISSUE THREAD

**Issue by sampaccoud** [openfun/richie#363]
## Feature Request

We would like to be able to publish a course glimpse for any course on any page of the CMS.

**Describe the solution you'd like**

Add a course plugin similar to the existing Person and Organization plugins.
Use the existing course glimpse fragment to display the course glimpse.

**Comment by 2018D** [comment]
I'll start working on this.

**Comment by 2018D** [comment]
There now is a pr #406 for this.
