### ISSUE TITLE
Improve filtering in the filters pane on the Search view

### ISSUE THREAD

**Issue by mbenadda** [openfun/richie#376]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
Right now the search filters pane is pretty crude. The basic functionality is there (for organizations and subjects) but we're missing key parts and the experience is not great.

**Describe the solution you'd like**
- Implement the filters for other facets
  The filters are not implemented nor the facets displayed for other dimensions than organizations & subjects. They are available on the backend and just need to be plugged in here.

- Improve the readability of active filters
  Active filters are displayed at the top of their category and are made bolder. This is not enough to distinguish them. We need to add eg. a ticked box in the place where their facet count would be to make it obvious they are enabled.
  We can additionally list some active filters with an icon to remove them directly in the search box. This can be somewhat more complex (we need to scale it when users add a lot of filters) and is therefore a lower priority.

- Support more than 10 values for the organizations & subjects categories.
  The existing implementation is just picking up whatever the backend is returning as top facets for this category. This is fine as a default view, but we need to be able to filter by other values straight from the filters pane.
  We can do this by adding a small autosuggest field below the list of top filter values. Ideally it would display facet counts along with the suggestions. As a first version, we can use the generic endpoints and not display any counts.

**Describe alternatives you've considered**
Any other suggestions for improving the experience and exhaustiveness of our search filters is welcome.

**Discovery, Documentation, Adoption, Migration Strategy**
All of the suggestions above add visual elements and should be easy to discover this way. Of note: existing implementations might not be completely accessible: any refactors should look to improve on this. We need our search to be as accessible as possible.

**Do you want to work on it through a Pull Request?**
Yes. Also meant as proposals for @lunika to pick from.

- [x] Filters for Language, Availability & New courses are implemented
- [x] Active filters are more distinguishable
- [x] Non-top-10 organizations & subjects can be added to filters through a search box
- [x] They show facet counts
- [ ] Search box shows a (redundant) list of active filters

**Comment by lunika** [comment]
> Implement the filters for other facets
>The filters are not implemented nor the facets displayed for other dimensions than organizations & subjects. They are available on the backend and just need to be plugged in here.

I would like to work on this point. Where can I found the api resources related to current harcoded filters ? I saw there is a documentation for the [search endpoints](https://github.com/openfun/richie/blob/master/src/richie/apps/search/description.apib) and I see nothing related to `availatbility`, `language` or `new` resources. 

Is it possible to have the endpoint and a payload example for each resources allowing me to implement it in the front application ? Or maybe the good documentation is somewhere else and I didn't see it.

Thanks.

**Comment by mbenadda** [comment]
Unfortunately these docs are not up-to-date; I created #382 to fix this.

In the meantime you can just inspect the Response for the `/api/v1.0/courses` request. It contains facets and facet counts for the other dimensions.

Facets & values along with relevant messages are already available in [settings](https://github.com/openfun/richie/blob/master/src/richie-front/js/settings.ts) through `FILTERS_HARDCODED`.

For the outgoing requests, you need to reuse the machine names for filters & values.

**Comment by mbenadda** [comment]
This can be closed: everything was done but the last bullet point which has its own expanded issue.
