### ISSUE TITLE
Missing translations ?

### ISSUE THREAD

**Issue by lunika** [openfun/richie#379]
## Bug Report

**Expected behavior/code**
I use richie with the french language. Every thing is translated except the search page.

**Actual Behavior**

The search page is not translated

**Steps to Reproduce**
1. switch to french
2. go to search page

**Environment**
- Richie version: master branch
- Platform: I'm using the docker-compose env provided in this repo.

**Additional context/Screenshots**

![screenshot_2018-10-04 cours](https://user-images.githubusercontent.com/767834/46462171-00276f00-c7c1-11e8-8ecb-d655fca0e13d.png)

**Comment by mbenadda** [comment]
Hey @lunika,

Thanks for your report. This is a known issue. The relevant functionality has not been completely implemented yet.

It is already documented, see #89 for more details.

**Comment by mbenadda** [comment]
Close as duplicate.
