### ISSUE TITLE
enable redux devtools by default

### ISSUE THREAD

**Issue by lunika** [openfun/richie#383]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**

Richie front application uses Redux. There is a lot of tools available to improve the developer experience when using redux. One of the most famous (and most used) is [redux devtools](https://github.com/zalmoxisus/redux-devtools-extension). 

To use it, you should configure it in your redux store, so you must, programmatically, add dedicated code in your codebase to allow its usage. In your codebase, it should be [here](https://github.com/openfun/richie/blob/master/src/richie-front/js/data/configureStore.ts). Without this modification it is not allow to use redux devtools.

**Describe the solution you'd like**

For a better developer experience, it should be great to configure, by default, the usage of this tool. I've created a PR for this (#381) but this one will not be merged as is because openfun's team does not want to ship this code in production.

The configuration needed is explain [here](https://github.com/zalmoxisus/redux-devtools-extension#12-advanced-store-setup) and it can be use as is in production.

**Describe alternatives you've considered**

An alternative can be to configure the tool to be only enabled in development.
There is a dedicated chapter in the documentation about using it in production : https://github.com/zalmoxisus/redux-devtools-extension#14-using-in-production
You should also read this article, explaining why it is not bad to have this code in your production environment : https://medium.com/@zalmoxis/using-redux-devtools-in-production-4c5b56c5600f

**Discovery, Documentation, Adoption, Migration Strategy**

There will be nothing to do. Richie will be configured to use redux devtools and if a new developer wants to contribute he has nothing to do.

**Do you want to work on it through a Pull Request?**

A PR already exists #381

**Comment by mbenadda** [comment]
I'm closing this (like I closed #381) because we're not using `redux` anymore.
