### ISSUE TITLE
Allow configuration of resource-based filter number of displayed values in search

### ISSUE THREAD

**Issue by mbenadda** [openfun/richie#405]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
When we do a search request on courses, we only display up to 10 available filter values for each resource-based filter. This is implicit as it is the default number returned by the terms aggregation in elasticsearch.

We therefore hardcoded 10 as the cap on the number of filter values we display when the facet counts are not available.

We should make this value configurable instead of implicitly forcing it.

**Describe the solution you'd like**
Add a ~frontend setting & a corresponding~ backend setting for the cap on the number of facets/filter values. Use them in ~our UI and In~ our elasticsearch query builder.

**Describe alternatives you've considered**
N/A

**Discovery, Documentation, Adoption, Migration Strategy**
Since it's a new setting, some comments to go along with it there should be enough.

**Do you want to work on it through a Pull Request?**
👍

**Comment by sampaccoud** [comment]
This was fixed by PR https://github.com/openfun/richie/pull/767
