### ISSUE TITLE
Remove course setting menu from course page

### ISSUE THREAD

**Issue by 2018D** [openfun/richie#414]
## Feature Request
This feature request is a reminder to eventually remove it.

**Is your feature request related to a problem or unsupported use case? Please describe.**
I noticed that the course page still has a course setting menu. It is now useless since we refactored everything out of it.

**Describe the solution you'd like**
Remove the course setting menu from the course page admin menu.

**Describe alternatives you've considered**
None really.

**Comment by sampaccoud** [comment]
:+1: and do the same on the person page and on the subject page. The organization page still has one field in it... maybe it could be removed as well in the future.

**Comment by 2018D** [comment]
Well, i just went through this again:
- [ ] Course
- [ ] Subject
- [ ] Person - Page title, Slug are duplicate of Title, Name and Last Name
- [ ] Organization - has the code value

**Comment by sampaccoud** [comment]
Closing this issue as:
- the course settings page now has 3 fields: effort, duration and flag to list a course in the catalog or not.
- the category settings page allow to define a color for this category.
