### ISSUE TITLE
Add a link on the course run page to easily go back to the related course page

### ISSUE THREAD

**Issue by sampaccoud** [openfun/richie#415]
## Feature Request

https://github.com/openfun/richie/pull/410 is adding a specific page for each course run. We need to add a link to easily go back to the related course.

**Describe the solution you'd like**
I was thinking to add this link as a breadcrumb on top of the page content zone.

**Describe alternatives you've considered**
Add a simple button?

**Discovery, Documentation, Adoption, Migration Strategy**
This breadcrumb would be available on the search page, the course page and the course run page. The snapshot page which can exist between the course page and the course run page should not materialize as a step in the breadcrumb (it's content is already displayed on the course run page):
> search > my course tile > course run 1

**Comment by sampaccoud** [comment]
@2018D do we consider that the breadcrumb has solved this issue?

**Comment by 2018D** [comment]
Yes it has.
