### ISSUE TITLE
Make autosuggestion diacritics-insensitive

### ISSUE THREAD

**Issue by mbenadda** [openfun/richie#419]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
Autosuggestion as it works right now does not return results with diacritics for a query without diacritics, and vice-versa.

**Describe the solution you'd like**
A search for `"meca"` should return a result including `"Mécanique"`. Same thing the other way around. Also the first four characters in our example string `"Mécanique"` should be highlighted.

- Using language specific analyzers without stop words should fix our accenting issues while still keeping the predictable behavior from the `simple` analyzer.
- We'll be using ES `highlight` to implement the bold highlighting (see [the docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-highlighting.html)) as removing diacritics in JS is extremely cumbersome.

**Describe alternatives you've considered**
[This](https://yarnpkg.com/en/package/diacritics-map) is the best thing I found to remove diacritics in JS. Enough said.

**Discovery, Documentation, Adoption, Migration Strategy**
- more suggestions will appear in autosuggest, where the user already expects them;
- bold highlights are pretty obvious and the solution we already went for in our first insufficient attempt (in #418, see [the removed commit](https://github.com/openfun/richie/pull/418/commits/7a2e9b1c9876df5a7506e62e3e4847c201a9f4fa))

**Do you want to work on it through a Pull Request?**
👍

**Comment by sampaccoud** [comment]
May I add that all these improvements that we are going to make to the search index to improve search results could be the subject of targetted ES tests:

- generate significative content for the targetted case,
- index this content is ES using our mappings,
- validate that the query returns the expected results.
