### ISSUE TITLE
Add a field to indicate the languages in which a course is available.

### ISSUE THREAD

**Issue by sampaccoud** [openfun/richie#425]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
We need to be able to indicate, on the course syllabus, the languages in which the course content is available.

**Describe the solution you'd like**
I think this field should be on the course run object because each course run could be available in different languages. In particular, edX does not support multilingual course content, so the way to do multilingual courses could be to open several course runs, each one for a specific language.

Technically, the `languages` field could be a Django `ArrayField` of `CharField` with a list of ISO 639 languages as choices.

**Discovery, Documentation, Adoption, Migration Strategy**

- [x] The languages field should be required to create a course run,
- [x] We should add a field to select multiple languages on the CMS wizard form to create new course runs,
- [x] The list of languages should be displayed and editable on the course pages and on the course run pages,
- [x] ~Language should be a filter on the search page. It should be linked to the dates of the related course run so that when we filter by a language and a status, we only see the courses that have a course in this status for the selected language.~ The language filter on the search page should be made a facet.

**Do you want to work on it through a Pull Request?**
:+1:

**Comment by mbenadda** [comment]
This seems like a fine solution to me 👍.

We'll just have to be careful to return the "most correct" course run per language & display it in the "most correct" language available when we generate search results for courses with a language filter.

**Comment by robertgerinlajoie** [comment]
Hi, good point. Some observations.

1- I take for granted an equivalent search page like the edX one, see https://www.edx.org/course/?, and where we can search for course langage and other fields.

2- to be more precise, we should use internally only the ISO-639-1, the 2 letters code, and not mention the country specific locale. And as a parameter for Ritchie admin, we should be able to specify the preferred suggested langage (french, english, ...) in front of the complete langage list;

**Comment by sampaccoud** [comment]
Hi @robertgerinlajoie! 
Some elements of answer:

1. yes, that's what we have in mind. Contrary to the search engine you link, we will be able to filter on one but also on several languages,
2. Whether you use ISO 639-1 two-letter codes or country+language locales is up-to-you in Django. It depends on what you declare in the `LANGUAGES` setting. The preferred language in Django is also configurable via the `LANGUAGE_CODE` setting and could be either a two-letter language or a full locale if I'm not mistaken.

Please note that your CMS pages will be translated in some languages: maybe english and french for example. But you should still be able to declare a course run in other languages in which your CMS pages are not translated. So the language field on the course run should propose all the languages defined in ISO 639 and not just the few languages activated in your CMS. Are we in line on this as well?

**Comment by mbenadda** [comment]
Yes, it will also let me get back into this after the changes you made for the index.

**Comment by sampaccoud** [comment]
We moved back to indexing courses instead of course runs. PR https://github.com/openfun/richie/pull/496 finalizes this issue as languages are now a facet and filters through a nested field via a painless script.
