### ISSUE TITLE
Filter choice duplication

### ISSUE THREAD

**Issue by sampaccoud** [openfun/richie#484]
## Bug Report

**Expected behavior/code**
A filter choice that is already selected should not be proposed as a filter in autocomplete suggestions.

**Actual Behavior**
A filter choice that is already selected is still proposed in autocomplete suggestions. If we select the suggestion, the filter choice gets **duplicated** in the left side bar filters.

**Steps to Reproduce**
1. Load the search page
2. Click on an organization in the filter of the left side bar
3. Now start typing the name of this same organization
4. The autocomplete suggestions proposes the organization > **IT SHOULD NOT**
5. Click on the suggestion > The filter choice gets duplicated. It should not. But this might not be the problem to fix if we solve the problem in 4.

**Environment**
Richie version: 1.0.0-beta.1

**Comment by mbenadda** [comment]
Fixed in #502 by taking care of `5.` directly
