### ISSUE TITLE
Sass watcher does not see source changes

### ISSUE THREAD

**Issue by sveetch** [openfun/richie#499]
## Bug Report

**Expected behavior/code**
When launching `make watch-sass`, a change on any registered Sass source should trigger a build.

**Actual Behavior**
Currently `watch-sass` does not see when a Sass source from an app is changed and so it does not perform a new build.

**Steps to Reproduce**
1. Launch `make watch-sass`
2. Open and edit any Sass source like `apps/courses/templates/courses/cms/_organization_list.scss`
3. No build is triggered

**Environment**
- Richie version: 1.0.0-beta.1
- Platform: Ubuntu 18.04.2 LTS
- Docker: 18.06.1-ce (build e68fc7a)

**Possible Solution**
I don't really searched for a workaround yet, maybe something with inode from the container ?

**Comment by sveetch** [comment]
Updated details since this only happen on sources from apps, rebuild is correctly triggered when a change occurs from `frontend/scss`

**Comment by jmaupetit** [comment]
:thinking: so that should be easy to fix by adding supplementary paths to watch to the `nodemon` command (`-w path/to/foo` option).

See https://github.com/openfun/richie/blob/master/src/frontend/package.json#L13

**Comment by sveetch** [comment]
Just tried:

`nodemon -e scss -w src/richie/apps/ -x 'yarn sass'`

And it results not any source triggers a rebuild, even on something like `src/frontend/scss/_main.scss` that worked before.

**Comment by jmaupetit** [comment]
My bet is that in this case, you must define multiple paths, _e.g._ including `src/richie/frontend`
