### ISSUE TITLE
Language name aren't properly translated when using settings.ALL_LANGUAGES

### ISSUE THREAD

**Issue by 2018D** [openfun/richie#527]
## Bug Report

**Expected behavior/code**
The language name should be translated when using settings.ALL_LANGUAGES as we do in course_run

**Actual Behavior**
They are not.

**Steps to Reproduce**

1. Make demo-site
2. Make compilemessages
3. Make stop, make run
4. Visit a course or course run.

**Environment**
- Richie version: master
- Platform: demo makefile

**Possible Solution**

**Additional context/Screenshots**
![Screenshot_2019-03-13 Le plaisir de concrétiser vos projets plus rapidement](https://user-images.githubusercontent.com/17911549/54295230-ffbdac00-4588-11e9-9dd8-49973457e348.png)

**Comment by sampaccoud** [comment]
I think this is a classical case with Django LANGUAGES. They are defined in [global_settings/](https://github.com/django/django/blob/master/django/conf/global_settings.py) and wrapped in a noop gettext function.
So the translations are available in Django's .po files but the settings will not get translated unless you call the real lazy translation function. 
The fix should be something like:
```python
ALL_LANGUAGES = [(language, _(name)) for language, name in Configuration.LANGUAGES]
```

@2018D do you want to test the fix and make a PR?

**Comment by 2018D** [comment]
This has been completed with #538
