### ISSUE TITLE
Cosmetic improvements

### ISSUE THREAD

**Issue by sampaccoud** [openfun/richie#540]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**

1) Blue on Blue is not good for accessibility:
    * "Course Runs" on the course detail page, *
    * "Fitler courses" on the search page
2) Links to social networks are missing on the course detail page (also need on blog post pages),
3) A language selector is missing in the header
4) The vertical spacing between sections on the course detail page is too big.

**Describe the solution you'd like**

I propose to:
- [x] change to "white on blue",
- [x] I think we need a ~plugin~ setting to define social networks for each location so that it is configurable for each instance,
- [x] add language selection via links at the top right of the page,
- [x] reduce spacing.

**Comment by sveetch** [comment]
@sampaccoud _I think we need a plugin to add social networks so that it is configurable for each instance_ so something like with Licence, where you create some object from Django admin then you can select them from LicencePlugin to drop them in a placeholder ?

**Comment by sampaccoud** [comment]
@sveetch agreed! I saw that there are some existing plugins for this. Maybe some of them are fit for this.

**Comment by sveetch** [comment]
Minor integrations changes has been done, @2018D already works on menu language, still rest the social network menu that finally won't be a plugin, a simple templatetag linked to a settings for available networks will be enough, templates (courses and blogpost?) that require a networks menu will just have to include it.
