### ISSUE TITLE
Add list of categories page

### ISSUE THREAD

**Issue by sampaccoud** [openfun/richie#541]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
Categories are a taxonomy that needs to be displayed on the page `/en/categories/`.

**Describe the solution you'd like**
- [x] Add a template that displays the whole nested structure of categories. The first level is a meta category (=filter on the search page), the immediate children are top level categories.
- [x] Add basic styling

**Comment by sveetch** [comment]
Resume from previous episodes: Finally we won't show full nested tree of every categories. Instead the /categories/ will only show top level categories then in each category detail we will have a "Sub categories" block which show direct children of current category.
