### ISSUE TITLE
Improve styling images

### ISSUE THREAD

**Issue by sampaccoud** [openfun/richie#567]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
Some configuration is missing to allow controlling the positioning of images.

**Describe the solution you'd like**
- Adding images from CKEditor:
    * remove the useless "image" button,
    * when adding an image via the "plugin" bouton:
        - allow horizontal alignment via the 3 CKEditor alignment buttons: it works but the button doesn't show it's pressed...
        - allow applying horizontal alignment on the image itself: this should result in a floating image behavior.
- Addition images directly from a plugin: allow applying horizontal alignment on the image plugin itself that should result in a floating image.

When adding a legend it should be centered below the image (it is currenlty left aligned).

**Comment by sveetch** [comment]
- [ ] Update Ckeditor configs to disable ckeditor image plugin;
- [ ] Fix CKeditor text alignment button (need to add alignment styles to ckeditor css?);
- [ ] Write djangocms-picture css styles for image alignment (align-left, align-right, align-center);
- [ ] Legend (figure ? caption?);
- [ ] Ensure there is a default `max-width: 100%` on basic `img` style (Bootstrap does not do that?);

**Comment by sveetch** [comment]
Done in #594
