### ISSUE TITLE
Invalid image file breaks Elasticsearch index generation

### ISSUE THREAD

**Issue by sampaccoud** [openfun/richie#570]
## Bug Report

**Expected behavior/code**
If an invalid image is uploaded e.g. as course cover, it should be ignored and not break the command to generate the Elasticsearch index.

**Actual Behavior**

```
    silent_template_exception=silent_template_exception)
  File "/usr/local/lib/python3.7/site-packages/easy_thumbnails/files.py", line 388, in generate_thumbnail
    "The source file does not appear to be an image")
easy_thumbnails.exceptions.InvalidImageFormatError: The source file does not appear to be an image
Sentry is attempting to send 0 pending error messages
Waiting up to 2.0 seconds
Press Ctrl-C to quit
```

**Steps to Reproduce**
1. upload an invalid image as course cover
2. try regenerating ES index:  make search-index
3. And then the bug happens!

**Environment**
- Richie version: 1.0.0-beta.3
- Platform: docker

**Possible Solution**
- [ ] Add a try/except here:  https://github.com/openfun/richie/blob/master/src/richie/apps/search/indexers/courses.py#L367
- [ ] Add test to secure behavior

The same fix must be applied for the categories and organizations indexers:
- categories: https://github.com/openfun/richie/blob/master/src/richie/apps/search/indexers/categories.py#L84
- organzations: https://github.com/openfun/richie/blob/master/src/richie/apps/search/indexers/organizations.py#L76

**Comment by jmaupetit** [comment]
Can you define what an "invalid image" is? Is this a broken image file or a file with the wrong mime-type?

Maybe using a library based on `libmagic` [1] could help detecting if the uploaded file is valid?

[1] https://github.com/ahupp/python-magic
