### ISSUE TITLE
Show only the dates for an archived course run

### ISSUE THREAD

**Issue by sampaccoud** [openfun/richie#574]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
The support team worries that some of our courses have more than 10 course runs. They will all display on the course page...

**Describe the solution you'd like**
Don't show the archived course runs with the full details and a button. Instead, add a section to the right side bar called "Archived runs" and list all archived course runs with just a link mentioning their past dates "from Aug. 3, 2018 to Sept. 5 2018".

Same for course runs that are still open but closed for enrollment with a section "On-going runs".
Same for course runs that are not yet open for enrollment with a section "Coming soon".

**Comment by sampaccoud** [comment]
![related course runs](https://user-images.githubusercontent.com/1427165/55726024-2c8da380-5a0f-11e9-8e84-baf7e1d91f68.png)

**Comment by 2018D** [comment]
I'm testing a solution by doing the seperation only on the template:
https://github.com/openfun/richie/compare/course_run_presentation
Does this work or would you rather have the seperation done on the backend ?

**Comment by sampaccoud** [comment]
I think it works like this... 
Performance will probably be an issue when you scale the number of runs... What we should probably do is subqueries to get archived, opened, coming etc. sessions for a course via a db filter instead of looping on all the runs and going through the algorithm for each of them to determine its state... (like archived course runs are runs for which end_date > now).

**Comment by 2018D** [comment]
I'll start sorting it in the backend. I was indeed worried about performance issues.
I'll let you know when i'll have some code for you to look at.

**Comment by 2018D** [comment]
New code. it will need some test. But so far, it looks good to me.
Have a look let me know what you think. Am i on the right track?
https://github.com/openfun/richie/compare/course_run_presentation
