### ISSUE TITLE
Pagination in page list templates

### ISSUE THREAD

**Issue by sveetch** [openfun/richie#580]
## Feature Request

It appears that pagination inside page list is really needed, even more with recent blogpost model addition, since it is common to have multiple entries in a blog and so blogpost list should be paginated to avoid loading everything.

**Describe the solution you'd like**
I didn't have a real concrete solution yet, since we are talking about pagination inside a cms page on its child objects.

So we need to create a new listing object (since `Page.get_child_pages` is from djangocms code) that would be using the Pagination object from Django. Problem is we don't have hands on a page view, and the pagination need to reach the request to get the "GET" attributes to find url arguments about required page number (`?page=42`).

Once a Pagination object is working and available inside template, we can use it to display a list of available page numbers (and possibly the previous/next item).

**Do you want to work on it through a Pull Request?**
Why not.

**Comment by sveetch** [comment]
New pull request #822 should close this issue when merged.

**Comment by sampaccoud** [comment]
Solved by PR https://github.com/openfun/richie/pull/822. We now use [dj-pagination](https://github.com/pydanny/dj-pagination) to paginate list pages and related objects on detail pages.
