### ISSUE TITLE
Clicking on a search suggestion crashes the frontend app

### ISSUE THREAD

**Issue by jmaupetit** [openfun/richie#582]
## Bug Report

**Expected behavior/code**

When clicking on a search suggestion, we expect to filter the search given clicked suggestion.

**Actual Behavior**

The frontend app crashes and a blank screen shows.

**Steps to Reproduce**

1. Go to the courses page, _e.g._ https://richie.education/fr/cours/
2. Type `arti`, click on the "Adaptive bandwidth-monitored artificial intelligence" suggestion
3. :boom: the frontend app just crashed

**Environment**

- Richie version: at least from `7051ab0` and probably before
- Platform: all

**Additional context/Screenshots**

![richie-text-search-fail](https://user-images.githubusercontent.com/956157/55341805-95bd6600-54a7-11e9-8a1b-1ec87ba364be.gif)

**Comment by lunika** [comment]
I think this is fixed in #563 the frontend deployed does not used the refactor made in the backend.
