### ISSUE TITLE
About assets minification and packing

### ISSUE THREAD

**Issue by sveetch** [openfun/richie#590]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**

There is currently no real assets packing or minification. Admittedly frontend library is naturally packed to an unique file and frontend CSS is compiled to an unique file.

But there is not minification at all. We actually got a `main.css` at ~152Ko and `richie/js/index.js` is around 2,3Mo ! With minification we could win around at least 40% for each file.

**Describe the solution you'd like**
Minification is something to reserve only for production, since in development we need sometime to read the source. So frontend configs for js and sass compilers should use something like a variable environment about production deployment.

**Describe alternatives you've considered**

There is also some Django apps to manage assets from a manifest and is able to proceed to packing and minification during the Django "collectstatics" process.

**Discovery, Documentation, Adoption, Migration Strategy**
* https://webassets.readthedocs.io/en/latest/ (the one we use at Emencia)
* https://django-pipeline.readthedocs.io/en/latest/
* https://django-compressor.readthedocs.io/en/stable/

**Do you want to work on it through a Pull Request?**
I can help if needed.

**Comment by jmaupetit** [comment]
I would prefer achieving the minification task with a frontend stack. This should be automated and thus be translated in a new frontend-related job in the CI.

**Comment by jmaupetit** [comment]
Also we need to generate related `.map` fileS.

**Comment by sveetch** [comment]
@jmaupetit https://github.com/sass/node-sass#sourcemap

**Comment by mbenadda** [comment]
Assets are already minified (see demo on https://richie.education)
