### ISSUE TITLE
Add a breadcrumb on course pages

### ISSUE THREAD

**Issue by sampaccoud** [openfun/richie#611]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
It is not always obvious how to navigate inside courses / snapshots / course runs.

**Describe the solution you'd like**
We need to add breadcrumbs on the course pages:
- Course: Home / Courses / Course title
- Snapshot:  Home / Courses / Course title / timestamp
- Course run: Home / Courses / Course title / Course run title  (if it is below a snapshot, the snapshot should still not appear in the breadcrumb)

**Describe alternatives you've considered**
Should we consider breadcrumbs on other types of pages as well?

**Comment by sveetch** [comment]
Breadcrumbs serve as an effective visual aid, it's an additional information about context, like a menu it should be always present in every page or not at all.

But, breadcrumbs meaning is only about hierarchy, so it is almost useless to display it on top level pages like homepage or over pages that are linked top level menu. Also commonly we avoid to display current page in breadcrumbs. Sometime we show it without a link (or disabled).

**Comment by sveetch** [comment]
This has been done and merge with PR #821
