### ISSUE TITLE
Course glimpse from course search page miss new element for empty cover

### ISSUE THREAD

**Issue by sveetch** [openfun/richie#638]
## Bug Report

**Expected behavior/code**
With last commit from PR #637, course glimpse have a new element `<div class="course-glimpse__media__empty">{% trans "Cover" %}</div>` instead of `<img>` when course does not have a cover image. It should be available course glimpse without a cover.

**Actual Behavior**
Course search page from react frontend does not include this new element yet.

**Steps to Reproduce**
1. Test the PR #637 or wait for it to be merged in master
2. Create a empty new course or edit one to remove its cover image;
3. Make sure this course is added to the "Popular courses" section from homepage;
4. Go to homepage, course without cover display an grey square with "Cover" word;
5. Go to /courses/, the same course without cover does not display grey square;

**Environment**
- Richie version:
- Platform:

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by sampaccoud** [comment]
I think the scope of this issue should be to harmonize the glimpse shown on the search page with the glimpse shown elsewhere in the CMS.
