### ISSUE TITLE
query is counted as a selected filter

### ISSUE THREAD

**Issue by sampaccoud** [openfun/richie#715]
## Bug Report

**Expected behavior/code**
We do not expect the fulltext query to be counted as a filter in the link `clear 1 selected filter` at the top of the left side filter bar.

**Actual Behavior**
a full text query currently counts as a `selected filter`.

**Steps to Reproduce**
1. go to https://richie.education/en/courses/
2. Type something in the search input
3. See that the link `clear 1 selected filter` appears at the top of the left side bar

**Environment**
- Richie version: 1.0.0
- Platform: https://richie.education

**Possible Solution**
exclude the query filter from the count.

**Comment by mbenadda** [comment]
I actually thought this was expected to "count" as a clearable filter
