### ISSUE TITLE
Consider moving search app templates to the django app directory

### ISSUE THREAD

**Issue by jmaupetit** [openfun/richie#72]
## Purpose

`search` app templates are stored in the main templates directory, _e.g._ `richie/templates/search/`. IMO, this is a bit disturbing for a recent Django project.

## Proposal

Let's move them to the application directory, _e.g._ `apps/search/templates/search`.

**Comment by sampaccoud** [comment]
The idea we discussed with @mbenadda is:

- let the "search" app be a Rest service
- declare the "search" app as a dependency of the "courses" application
- include the frontend of the search in the "courses" application

**Comment by jmaupetit** [comment]
This makes sense. For clarification, can you describe the application tree we will be moving to?

**Comment by mbenadda** [comment]
The question remains of how to distribute the frontend sources — and, if it is distributed separately (in eg. `yarn`/`npm`), how to split `scss` files between that and the `courses` app.

The issue with distributing it through a Django app is that consumers may need to do some grueling contorsions to run their own webpack build to override the settings or extend the JS.
