### ISSUE TITLE
Allow the footer to be split in several columns

### ISSUE THREAD

**Issue by sampaccoud** [openfun/richie#823]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
We want to be able to split the footer in several columns.

![Montage_pied_de_page_3](https://user-images.githubusercontent.com/1427165/64875686-e7207280-d64d-11e9-929d-e04ba4ed4938.png)

**Describe the solution you'd like**
The number of columns could be determined by the number of pages below the root footer page. Their children would then be the links.

**Comment by sveetch** [comment]
@sampaccoud you mean to determine columns count depending computed multiple from page count ? Or you mean choosing number of columns from page count total (if > 5: two column, if > 10: four column, etc..) ?

By the way, i don't think this is a good idea to let automatically split columns, this should be something statically defined in template and css. Responsive behavior will be hard to implement correctly with dynamical number of columns.

**Comment by sveetch** [comment]
@sampaccoud i just looked on ongoing homepage mockup, annexes pages is clearly splitted in three columns and don't allow for more (no more space left).

**Comment by sampaccoud** [comment]
@sveetch what I meant was that today we have the following pages:
```
Annex
    About
    Sitemap
```
That renders on one line in the footer: "About   Sitemap"

What we want is the following pages to render in 2 columns:
```
Annex
    Column 1
        Item 1-1
        Item 1-2
    Column2
        Item 2-1
        Item 2-2
```
The number of columns in the footer should adapt to the number of pages below "Annex" and it is up to the site administrator to adjust the number of columns to the place left by the css and the length of each pages' title.

**Comment by sampaccoud** [comment]
This feature was introduced by https://github.com/openfun/richie/pull/836
