### ISSUE TITLE
Course runs are referenced in sitemap.xml

### ISSUE THREAD

**Issue by sveetch** [openfun/richie#824]
## Bug Report

**Expected behavior/code**
Since course run pages are not desired to be scanned from search engines, their urls should not be referenced in "sitemap.xml".

**Actual Behavior**
"sitemap.xml" does reference all course run pages.

**Steps to Reproduce**
1. Open https://richie.education/sitemap.xml
2. Search for a course run url (using a pattern like `/session-` should work)
3. And you can see they are all present

Warning, the sitemap.xml from the demo is huge and not human readable (everything on a same line). If you want to read it completely, save it as a file and put its source to https://htmlformatter.com/, then update previously saved file.

**Environment**
- Richie version: 1.8.3
- Platform: Any

**Comment by sveetch** [comment]
It will need to subclass `cms.sitemaps.CMSSitemap` in a new custom class which will override `CMSSitemap.items()` to filter out course run pages.

**Comment by sampaccoud** [comment]
This issue was solved by PR https://github.com/openfun/richie/pull/1202 as course runs are not CMS pages anymore.
