### ISSUE TITLE
All pages have HTML validation errors and warnings

### ISSUE THREAD

**Issue by sveetch** [openfun/richie#825]
## Bug Report

**Expected behavior/code**
All pages should pass the HTML validation without any error and possibly no warnings.

**Actual Behavior**
Take almost any page from a Richie website and give to the validator tool. An example:

https://validator.w3.org/nu/?showsource=yes&showoutline=yes&doc=https%3A%2F%2Frichie.education%2Ffr%2Fcategories%2Fniveau%2F

**Steps to Reproduce**
1. Copy a reachable (no localhost only) Richie url;
2. Paste it to the validator tool https://validator.w3.org/nu/
3. And scroll down to the report

**Environment**
- Richie version: 1.8.3
- Platform: Any

**Possible Solution**
Here are distinct messages which was found on pages.

- Error on `srcset` on `<img>` tags, caused by last ending comma in attribute value;
- Error on `sizes` on `<img>` tags, it seems every size item expect a leading media condition;
- Error on missing `alt` attribute on some `<img>` tags, we need to find template which build these tags to add the missing attribute, even if it's empty it is required;
- Error on `href` value on links with a `mailto` content which is not escaped and leading to include quote characters in attribute quotes;
- Error on obsolete `frameborder` attribute on the “iframe” element for teaser video course content, this is an old attribute commonly keeped for Internet Explorer <= 9, but since a long time we just can adjust iframe border from CSS (which is very often resolved with a global `border:0;` on iframe element);
- Warning on `type` attribute on `<script>` tags. Just need to remove them it's a deprecated attribute since HTML5, it's probably only in the base.html template;
- Warning on missing `lang` attribute on `<html>` tag. This is a useful thing for SEO and it's easy to implement, we already define this value from OG tags and it have to be done once in `base.html` template.

**Comment by sveetch** [comment]
Missing `lang` attribute on `<html>` should have been resolved with 1.9.0.

**Comment by sveetch** [comment]
I get it for the wrong value in `srcset` wichh end on a comma. It is because in thumbnail parts in templates we do something like this:

```
{% thumbnail picture 200x200 crop upscale subject_location=subject_location %} 200w,
{% if width >= 400 %}{% thumbnail picture 400x400 crop upscale subject_location=subject_location %} 400w,{% endif %}
{% if width >= 600 %}{% thumbnail picture 600x600 crop upscale subject_location=subject_location %} 600w{% endif %}
```

The serie of optional size within a `if` is not able to know about their state in the list of sizes. A quickfix should be to remove the comma from default size and each optional size would start with a comma and never end with a comma.

Also a templatetag to build the attribute value from given sizes as arguments should do it more cleanly. Something like:

```
{% thumbnail_sizes picture "200x200" "400x400" "600x600" %}
```

First argument would be assumed as the defaut size, other arguments as the optional ones. Only working on the parsed width from format "WIDTH[xHEIGHT]". Additional keyword argument could be able to be more flexible on using height instead of width or to enable/disable usage of "subject_location".

**Comment by sveetch** [comment]
Warning about deprecated `type` attribute on `<script>` tags is an easy go since there is only two tags involved in the `base.html`

**Comment by sampaccoud** [comment]
@sveetch you would need to pass also "width" to your template tags to make the "ifs"... I think it's not worth the hassle and will make templates less flexible and less explicit.

**Comment by sveetch** [comment]
Updated detail to add new finded errors.

**Comment by sveetch** [comment]
A clean hint about `sizes` attribute value correct syntax:

https://bitsofco.de/the-srcset-and-sizes-attributes/#thesizesattribute

It demonstrate that our `sizes` attribute values are often malformed since they start with the default size (the one without media condition) while syntax expect it at the end and the first size item to start with a media condition (except if there is only one item).

**Comment by sveetch** [comment]
I've potentially fixed everything but clearing the logs from many messages let me some another new minor messages:

- link element in button on homepage;
- probably too many h1 element on homepage;

I need some time to better review validator logs to update issue details and related pull request #838

**Comment by sveetch** [comment]
So i checked last reported issues:

- There is a `<button>` element inside `<a>` (used as glimpse item container) in course glimpse, which is forbidden and result to an error;  
- On homepage there is multiple `<h1>` on the same page. It results to a warning for accessibility since some screen readers and other tools use it as a top level document and so expect it to be unique;

I've updated pull request for additional tasks to resolve.

**Comment by sveetch** [comment]
Another one which should be the last now:

Invalid `role` value on pagination bullet list, `navigation` is not a valid value for `role` attribute on a `ul` element.

For reference : https://github.com/validator/validator/issues/157

Just put a `nav` element around bullet list and move `aria-labelledby` on the nav, this will resolve HTML valid and a right thing for accessibility.

Pull request has been updated to do so.

**Comment by sampaccoud** [comment]
Fixed by https://github.com/openfun/richie/pull/838
