### ISSUE TITLE
Bootstrap reboot stylesheet is imported twice

### ISSUE THREAD

**Issue by sveetch** [openfun/richie#867]
## Bug Report

**Expected behavior/code**
Bootstrap reboot stylesheet should be imported only once from Sass sources.

**Actual Behavior**
Currently the `main.scss` source imports Bootstrap reboot stylesheet twice:

https://github.com/openfun/richie/blob/fb0725cc3f9d78f9e3fdc192c7170b3060cfb08a/src/frontend/scss/_main.scss#L22

**Steps to Reproduce**
1. Open previously given url to file source
2. Look at line 18 and 22
3. You will see the same exact lines which import Bootstrap reset

**Environment**
- Richie version: 1.11.0
- Platform: Any

**Possible Solution**
Just remove the second identical lines.

**Comment by sampaccoud** [comment]
Solved by https://github.com/openfun/richie/pull/947
