### ISSUE TITLE
Allow category plugin variants

### ISSUE THREAD

**Issue by sampaccoud** [openfun/richie#884]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
In certain placeholders, we want to be able to choose different glimpse variants when adding a category on another page as a plugin.

**Describe the solution you'd like**
Implement the same solution as what was already done on courses (https://github.com/openfun/richie/pull/858) and organizations (https://github.com/openfun/richie/pull/786)

**Comment by sveetch** [comment]
Has been done during pull request for new demo integration since we normalized plugin and variants:

https://github.com/openfun/richie/blob/master/src/richie/apps/courses/cms_plugins.py#L98
