### ISSUE TITLE
Use TypeScript's `strict` mode

### ISSUE THREAD

**Issue by mbenadda** [openfun/richie#90]
TypeScript has a `strict` mode (nothing to do with the browser's) that enables stricter compilation errors, and will evolve over time as new, more stringent compiler options are added in. 

Right now it already enables a bunch of options we did not manually enable (https://www.typescriptlang.org/docs/handbook/compiler-options.html), the most significant of which is `strictNullChecks`.

We'll have to do some cleaning up after we enable it but it should help avoid errors.

**Comment by jmaupetit** [comment]
Fixed in #91
