### ISSUE TITLE
Pytest does not play the tests in the "plugings" directory

### ISSUE THREAD

**Issue by sampaccoud** [openfun/richie#93]
## Expected Behavior

Pytest and Django's test runner should run the same number of test.

## Actual Behavior

There are 6 tests that Django's test runner plays that are not played by pytest. I identified these 6 tests to be the ones for the "large_banner" plugin.

## Steps to Reproduce

The cause may be that the "plugins" directory has to be declared somewhere for pytest to consider it?

**Comment by mbenadda** [comment]
Pytest uses magic strings to discover tests. `tests.py` does not conform

> `pytest` will run all files of the form `test_*.py` or `*_test.py` in the current directory and its subdirectories. More generally, it follows standard test discovery rules.

from https://docs.pytest.org/en/latest/getting-started.html#run-multiple-tests

**Comment by sampaccoud** [comment]
Yep ! Actually I fixed it in this PR https://github.com/openfun/richie/pull/92

**Comment by sampaccoud** [comment]
Fixed in beda3175433592838a6ab7ee41b958f800898762
