### ISSUE TITLE
Main organization in elasticsearch

### ISSUE THREAD

**Issue by 2018D** [openfun/richie#950]
## Bug Report
Follow up of
https://github.com/openfun/richie/commit/22c7a27bc8f56e16774233c6a4847401de82bd7d

The main organization in elasticsearch is still using the first org in the index among the course's organizations and not the first org plugin in the course. I did not notice this at the time.

**Steps to Reproduce**

1. Have multiple organization
2. Have a course with multiple organization
3. Move the organization around (See that the main org has changed for the course and the course plugin) 
4. Reindex elasticsearch (See that it uses the first org in index among the course's org)

**Environment**
- Richie version: 1.16.1

**Additional context/Screenshots**
The workaround remains the same: have the index in a special order specific to your richie and it's courses.

**Comment by mbenadda** [comment]
Nice catch!

The bug was pretty subtle here, appearing as `course.get_organizations()` implementation changed with version `1.5.0`. Thanks for the report 👍
